// GENERATED by build-app-strings.js — which languages exist, and how complete.
// The Settings picker reads this; it must not depend on a table being loaded.
(function(g){ g.SD_APP_LANGS_AVAIL = {"en":{"have":587,"pct":100},"hi":{"have":554,"pct":94},"te":{"have":473,"pct":81},"kn":{"have":0,"pct":0},"ta":{"have":0,"pct":0},"bn":{"have":0,"pct":0},"mr":{"have":0,"pct":0},"gu":{"have":0,"pct":0},"as":{"have":0,"pct":0}}; })(typeof window!=='undefined'?window:global);
