// GENERATED by build-app-strings.js — which languages exist, and how complete.
// The Settings picker reads this; it must not depend on a table being loaded.
(function(g){ g.SD_APP_LANGS_AVAIL = {"en":{"have":675,"pct":100},"hi":{"have":642,"pct":95},"te":{"have":675,"pct":100},"kn":{"have":24,"pct":4},"ta":{"have":24,"pct":4},"bn":{"have":24,"pct":4},"mr":{"have":24,"pct":4},"gu":{"have":24,"pct":4},"as":{"have":24,"pct":4}}; })(typeof window!=='undefined'?window:global);
