// GENERATED by build-app-strings.js — which languages exist, and how complete.
// The Settings picker reads this; it must not depend on a table being loaded.
(function(g){ g.SD_APP_LANGS_AVAIL = {"en":{"have":972,"pct":100},"hi":{"have":972,"pct":100},"te":{"have":972,"pct":100},"kn":{"have":972,"pct":100},"ta":{"have":972,"pct":100},"bn":{"have":972,"pct":100},"mr":{"have":972,"pct":100},"gu":{"have":972,"pct":100},"as":{"have":24,"pct":2}}; })(typeof window!=='undefined'?window:global);
