// SHUBH DIN — Child & Family Report Content (EN+HI)
(function(g){var K={};
K.scoreBand={strong:{t_en:"Strong blessings for children",t_hi:"संतान हेतु प्रबल आशीर्वाद",en:"Your chart carries strong indications for the blessing of children — the 5th house and Jupiter, the significator of progeny, are well-placed. The joy of parenthood is warmly promised, and children may bring pride and fortune to the family.",hi:"आपकी कुंडली में संतान-सुख के प्रबल संकेत हैं — पंचम भाव और संतान-कारक गुरु शुभ स्थित हैं। माता-पिता बनने का आनंद सस्नेह वचनित है, और संतान परिवार में गौरव और सौभाग्य ला सकती है।"},good:{t_en:"Favourable for children",t_hi:"संतान हेतु अनुकूल",en:"Your chart is favourable for children — the significators are supportive, and the path to parenthood is smooth in the indicated periods. Timing matters more than possibility here; the favourable windows chapter shows the classically supported years.",hi:"आपकी कुंडली संतान हेतु अनुकूल है — कारक सहायक हैं, और संकेतित अवधियों में माता-पिता बनने का मार्ग सहज है। यहाँ संभावना से अधिक महत्व समय का है; शुभ-अवधि अध्याय शास्त्र-समर्थित वर्ष दर्शाता है।"},moderate:{t_en:"Blessings through patience",t_hi:"धैर्य से आशीर्वाद",en:"Your chart indicates the blessing of children comes with some patience — the significators ask for the right timing and, per tradition, the grace of Santan Gopal upasana. Many revered family lines began exactly so; medical wisdom and prayer walk well together.",hi:"आपकी कुंडली दर्शाती है कि संतान-सुख कुछ धैर्य से आता है — कारक सही समय और परंपरानुसार संतान-गोपाल उपासना की कृपा माँगते हैं। अनेक पूज्य वंश ऐसे ही आरंभ हुए; चिकित्सा-विवेक और प्रार्थना साथ चलते हैं।"},tender:{t_en:"A tender area — patience and grace",t_hi:"कोमल क्षेत्र — धैर्य एवं कृपा",en:"This is a tender area of your chart that asks for patience, faith and care. Challenging placements are never a verdict — they are an invitation to remedies, medical guidance and trust. With Santan Gopal upasana and the right timing, hope remains bright; consult both physicians and your family priest.",hi:"यह आपकी कुंडली का कोमल क्षेत्र है जो धैर्य, आस्था और देखभाल माँगता है। चुनौतीपूर्ण स्थितियाँ कभी निर्णय नहीं — वे उपाय, चिकित्सा-मार्गदर्शन और विश्वास का निमंत्रण हैं। संतान-गोपाल उपासना और सही समय से आशा उज्ज्वल रहती है; चिकित्सक और कुल-पुरोहित दोनों से परामर्श करें।"}};
K.jupiter={exalted:{en:"Jupiter, the great blessing-giver and significator of children, is exceptionally strong in your chart — a most auspicious placement for progeny, wisdom passing to the next generation, and joy through children.",hi:"गुरु, महान आशीर्वाद-दाता और संतान-कारक, आपकी कुंडली में असाधारण रूप से बली हैं — संतान, अगली पीढ़ी तक ज्ञान-संचरण और संतान से आनंद हेतु अत्यंत शुभ स्थिति।"},own:{en:"Jupiter sits in dignity in your chart — a strong, supportive placement for children and family happiness. The significator of progeny blesses this area of life well.",hi:"गुरु आपकी कुंडली में स्वगृही हैं — संतान और पारिवारिक सुख हेतु प्रबल, सहायक स्थिति। संतान-कारक इस जीवन-क्षेत्र को भली-भाँति आशीर्वादित करते हैं।"},neutral:{en:"Jupiter, the significator of children, holds a workable position in your chart. Its blessings flow well when supported by the favourable timing periods and traditional upasana.",hi:"संतान-कारक गुरु आपकी कुंडली में कार्यसाध्य स्थिति रखते हैं। शुभ-अवधि और परंपरागत उपासना के सहयोग से इनका आशीर्वाद अच्छी तरह प्रवाहित होता है।"},weak:{en:"Jupiter, the significator of children, is somewhat challenged in your chart — this asks for its strengthening through Guru upasana (Thursday worship, yellow offerings) and patience. Remedies genuinely help this placement.",hi:"संतान-कारक गुरु आपकी कुंडली में कुछ चुनौतीपूर्ण हैं — यह गुरु-उपासना (गुरुवार पूजन, पीत अर्पण) और धैर्य से इनके सशक्तीकरण की माँग करता है। उपाय इस स्थिति में सचमुच सहायक हैं।"}};
K.namingIntro={en:"In the Hindu tradition, a child's name is chosen to begin with a syllable drawn from the nakshatra (birth star) under which the child is born — this aligns the name with the child's cosmic vibration and is believed to support their fortune. Below are the auspicious starting syllables tied to the favourable nakshatras in your chart. When your child is born, their own birth-nakshatra will give the final syllable; a family priest can confirm it precisely.",hi:"हिंदू परंपरा में, संतान का नाम उस नक्षत्र से लिए गए अक्षर से आरंभ किया जाता है जिसमें संतान का जन्म होता है — यह नाम को संतान के ब्रह्मांडीय स्पंदन से जोड़ता है और उनके सौभाग्य का समर्थक माना जाता है। नीचे आपकी कुंडली के शुभ नक्षत्रों से जुड़े शुभ आरंभिक अक्षर हैं। संतान के जन्म पर उनका अपना जन्म-नक्षत्र अंतिम अक्षर देगा; कुल-पुरोहित इसे सटीक रूप से पुष्टि कर सकते हैं।"};
K.labels={
 title:{en:"Child & Family Report",hi:"संतान एवं परिवार रिपोर्ट"},
 subtitle:{en:"Progeny prospects, timing and auspicious naming",hi:"संतान संभावना, समय एवं शुभ नामकरण"},
 summary:{en:"Executive Summary",hi:"सारांश"},
 prospects:{en:"Children Prospects",hi:"संतान संभावना"},
 fifth:{en:"The 5th House & Jupiter",hi:"पंचम भाव एवं गुरु"},
 fifthIntro:{en:"In Vedic astrology, the 5th house governs children and Jupiter is their natural significator (Putra Karaka). Here is how they sit in your chart:",hi:"वैदिक ज्योतिष में पंचम भाव संतान का कारक है और गुरु उनके नैसर्गिक कारक (पुत्र कारक) हैं। आपकी कुंडली में इनकी स्थिति इस प्रकार है:"},
 windows:{en:"Favourable Periods for Children",hi:"संतान हेतु शुभ अवधियाँ"},
 whyWin:{en:"Why this period",hi:"यह अवधि क्यों"},
 naming:{en:"Auspicious Naming Syllables",hi:"शुभ नामकरण अक्षर"},
 nakLabel:{en:"Nakshatra",hi:"नक्षत्र"},
 syllables:{en:"Favourable starting sounds",hi:"शुभ आरंभिक अक्षर"},
 remedies:{en:"Remedies & Blessings",hi:"उपाय एवं आशीर्वाद"},
 method:{en:"Every rating derives from your computed 5th house strength (Ashtakavarga), Jupiter's dignity, and the Saptamsa (D7) chart — verify against your free Kundli report.",hi:"प्रत्येक अंक आपके गणना-कृत पंचम भाव बल (अष्टकवर्ग), गुरु की गरिमा और सप्तांश (D7) चक्र से व्युत्पन्न है — निःशुल्क कुंडली रिपोर्ट से सत्यापित करें।"},
 disclaimer:{en:"Offered in the spirit of tradition and hope, never as a medical statement. For family planning, please consult qualified physicians alongside spiritual guidance.",hi:"परंपरा और आशा की भावना से प्रस्तुत, कभी चिकित्सा-कथन के रूप में नहीं। परिवार-नियोजन हेतु कृपया आध्यात्मिक मार्गदर्शन के साथ योग्य चिकित्सकों से भी परामर्श करें।"}
};
g.SD_CHILD=K;})(typeof window!=='undefined'?window:global);
