// SHUBH DIN — 10-Year Forecast Content (EN+HI)
(function(g){var Y={};
Y.ratings={excellent:{t_en:"An excellent year",t_hi:"उत्कृष्ट वर्ष",en:"Benefic transits align strongly with your running period — expansion, opportunity and visible progress mark this year. Act boldly; the cosmos supports forward motion.",hi:"शुभ गोचर आपकी चल रही दशा से प्रबल मेल खाते हैं — विस्तार, अवसर और दृश्य प्रगति इस वर्ष की पहचान हैं। साहसपूर्वक कार्य करें; ब्रह्मांड आगे बढ़ने का समर्थन करता है।"},good:{t_en:"A favourable year",t_hi:"अनुकूल वर्ष",en:"Supportive influences outweigh the challenges — steady growth, good relationships and progress on goals are indicated. A year to build on with confidence.",hi:"सहायक प्रभाव चुनौतियों से भारी हैं — स्थिर वृद्धि, अच्छे संबंध और लक्ष्यों पर प्रगति के संकेत हैं। आत्मविश्वास से निर्माण का वर्ष।"},mixed:{t_en:"A mixed year",t_hi:"मिश्रित वर्ष",en:"A balanced year of both openings and lessons — progress comes with effort. Focus on your strengths, stay patient through slower phases, and steady work pays off.",hi:"अवसरों और पाठों का संतुलित वर्ष — प्रगति परिश्रम से आती है। अपनी शक्तियों पर ध्यान दें, धीमे चरणों में धैर्य रखें; स्थिर कार्य फल देता है।"},testing:{t_en:"A year of growth through effort",t_hi:"परिश्रम से विकास का वर्ष",en:"Some transits test your patience and foundations — this is Saturn-style growth, not misfortune. Discipline, health-care and steady effort turn this year into lasting strength.",hi:"कुछ गोचर आपके धैर्य और नींव की परीक्षा लेते हैं — यह दुर्भाग्य नहीं, शनि-शैली का विकास है। अनुशासन, स्वास्थ्य-देखभाल और स्थिर प्रयास इस वर्ष को स्थायी शक्ति में बदलते हैं।"},challenging:{t_en:"A year to consolidate",t_hi:"सुदृढ़ीकरण का वर्ष",en:"Several influences ask for caution and consolidation rather than expansion. Protect your health and resources, avoid big risks, lean on remedies — and you emerge stronger for the years ahead.",hi:"अनेक प्रभाव विस्तार के बजाय सावधानी और सुदृढ़ीकरण माँगते हैं। स्वास्थ्य व संसाधन सुरक्षित रखें, बड़े जोखिम टालें, उपायों का सहारा लें — और आगामी वर्षों हेतु अधिक सशक्त होकर निकलें।"}};
Y.domain={career:{en:"Career & Work",hi:"करियर एवं कार्य"},money:{en:"Money & Wealth",hi:"धन एवं संपत्ति"},relationships:{en:"Relationships & Family",hi:"संबंध एवं परिवार"},health:{en:"Health & Energy",hi:"स्वास्थ्य एवं ऊर्जा"}};
Y.theme={sun:{en:"authority, recognition and dealings with those in power",hi:"अधिकार, प्रतिष्ठा और सत्ताधारियों से व्यवहार"},moon:{en:"emotional matters, home, mother and public connection",hi:"भावनात्मक विषय, गृह, माता और जन-संपर्क"},mars:{en:"energy, courage, property and bold initiative",hi:"ऊर्जा, साहस, संपत्ति और साहसिक पहल"},mercury:{en:"communication, learning, business and skill-building",hi:"संवाद, अध्ययन, व्यापार और कौशल-निर्माण"},jupiter:{en:"wisdom, growth, teachers, finance and good fortune",hi:"ज्ञान, वृद्धि, गुरुजन, वित्त और सौभाग्य"},venus:{en:"relationships, comforts, arts and financial pleasures",hi:"संबंध, सुख, कला और आर्थिक आनंद"},saturn:{en:"discipline, responsibility, hard work and lasting foundations",hi:"अनुशासन, उत्तरदायित्व, परिश्रम और स्थायी नींव"},rahu:{en:"ambition, foreign matters, technology and unconventional gains",hi:"महत्वाकांक्षा, विदेश-विषय, तकनीक और अपरंपरागत लाभ"},ketu:{en:"introspection, spirituality, research and letting go",hi:"अंतर्मुखता, अध्यात्म, शोध और त्याग"}};
Y.action={excellent:{en:"Launch important initiatives, invest in growth, take opportunities",hi:"महत्वपूर्ण पहल आरंभ करें, वृद्धि में निवेश करें, अवसर लें"},good:{en:"Advance your goals steadily, strengthen key relationships",hi:"लक्ष्यों को स्थिर रूप से आगे बढ़ाएँ, प्रमुख संबंध मज़बूत करें"},mixed:{en:"Focus on strengths, avoid overextension, keep steady routines",hi:"शक्तियों पर ध्यान दें, अति से बचें, स्थिर दिनचर्या रखें"},testing:{en:"Prioritize health and discipline, avoid major risks, be patient",hi:"स्वास्थ्य व अनुशासन को प्राथमिकता दें, बड़े जोखिम टालें, धैर्य रखें"},challenging:{en:"Consolidate, protect resources, practise remedies, avoid big changes",hi:"सुदृढ़ करें, संसाधन सुरक्षित रखें, उपाय करें, बड़े बदलाव टालें"}};
Y.labels={
 title:{en:"10-Year Life Forecast",hi:"10-वर्षीय जीवन भविष्यवाणी"},
 subtitle:{en:"Year by year — dasha, transits and what to do",hi:"वर्ष-दर-वर्ष — दशा, गोचर और क्या करें"},
 overview:{en:"Your Decade at a Glance",hi:"आपका दशक एक दृष्टि में"},
 period:{en:"Running period",hi:"चल रही दशा"},
 theme:{en:"Year theme",hi:"वर्ष का स्वर"},
 domains:{en:"Life Areas This Year",hi:"इस वर्ष जीवन-क्षेत्र"},
 action:{en:"What to do",hi:"क्या करें"},
 jupiter:{en:"Jupiter",hi:"गुरु"}, saturn:{en:"Saturn",hi:"शनि"}, rahu:{en:"Rahu",hi:"राहु"},
 favourable:{en:"Favourable",hi:"अनुकूल"}, attention:{en:"Needs attention",hi:"ध्यान आवश्यक"}, steady:{en:"Steady",hi:"स्थिर"},
 method:{en:"Each year blends your Vimshottari dasha (maha & antar lords) with the house-positions of Jupiter, Saturn and Rahu counted from your Moon — the classical gochara method. Verify placements in your free Kundli report.",hi:"प्रत्येक वर्ष आपकी विंशोत्तरी दशा (महा व अंतर स्वामी) को चंद्र से गिने गुरु, शनि और राहु के भाव-स्थान से जोड़ता है — शास्त्रीय गोचर पद्धति। स्थितियाँ निःशुल्क कुंडली रिपोर्ट में सत्यापित करें।"},
 disclaimer:{en:"Offered in the spirit of tradition for reflection and planning. Your effort and choices shape how each influence unfolds.",hi:"परंपरा की भावना से चिंतन एवं योजना हेतु प्रस्तुत। आपका परिश्रम और निर्णय ही तय करते हैं कि प्रत्येक प्रभाव कैसे प्रकट होता है।"}
};
g.SD_FORECAST=Y;})(typeof window!=='undefined'?window:global);
