// SHUBH DIN — 10-Year Forecast Content (EN+HI)
(function(g){var Y={};
Y.ratings={excellent:{t_en:"An excellent year",t_hi:"उत्कृष्ट वर्ष",en:"Benefic transits align strongly with your running period — expansion, opportunity and visible progress mark this year. Act boldly; the cosmos supports forward motion.",hi:"शुभ गोचर आपकी चल रही दशा से प्रबल मेल खाते हैं — विस्तार, अवसर और दृश्य प्रगति इस वर्ष की पहचान हैं। साहसपूर्वक कार्य करें; ब्रह्मांड आगे बढ़ने का समर्थन करता है।"},good:{t_en:"A favourable year",t_hi:"अनुकूल वर्ष",en:"Supportive influences outweigh the challenges — steady growth, good relationships and progress on goals are indicated. A year to build on with confidence.",hi:"सहायक प्रभाव चुनौतियों से भारी हैं — स्थिर वृद्धि, अच्छे संबंध और लक्ष्यों पर प्रगति के संकेत हैं। आत्मविश्वास से निर्माण का वर्ष।"},mixed:{t_en:"A mixed year",t_hi:"मिश्रित वर्ष",en:"A balanced year of both openings and lessons — progress comes with effort. Focus on your strengths, stay patient through slower phases, and steady work pays off.",hi:"अवसरों और पाठों का संतुलित वर्ष — प्रगति परिश्रम से आती है। अपनी शक्तियों पर ध्यान दें, धीमे चरणों में धैर्य रखें; स्थिर कार्य फल देता है।"},testing:{t_en:"A year of growth through effort",t_hi:"परिश्रम से विकास का वर्ष",en:"Some transits test your patience and foundations — this is Saturn-style growth, not misfortune. Discipline, health-care and steady effort turn this year into lasting strength.",hi:"कुछ गोचर आपके धैर्य और नींव की परीक्षा लेते हैं — यह दुर्भाग्य नहीं, शनि-शैली का विकास है। अनुशासन, स्वास्थ्य-देखभाल और स्थिर प्रयास इस वर्ष को स्थायी शक्ति में बदलते हैं।"},challenging:{t_en:"A year to consolidate",t_hi:"सुदृढ़ीकरण का वर्ष",en:"Several influences ask for caution and consolidation rather than expansion. Protect your health and resources, avoid big risks, lean on remedies — and you emerge stronger for the years ahead.",hi:"अनेक प्रभाव विस्तार के बजाय सावधानी और सुदृढ़ीकरण माँगते हैं। स्वास्थ्य व संसाधन सुरक्षित रखें, बड़े जोखिम टालें, उपायों का सहारा लें — और आगामी वर्षों हेतु अधिक सशक्त होकर निकलें।"}};
Y.domain={career:{en:"Career & Work",hi:"करियर एवं कार्य"},money:{en:"Money & Wealth",hi:"धन एवं संपत्ति"},relationships:{en:"Relationships & Family",hi:"संबंध एवं परिवार"},health:{en:"Health & Energy",hi:"स्वास्थ्य एवं ऊर्जा"}};
Y.theme={sun:{en:"authority, recognition and dealings with those in power",hi:"अधिकार, प्रतिष्ठा और सत्ताधारियों से व्यवहार"},moon:{en:"emotional matters, home, mother and public connection",hi:"भावनात्मक विषय, गृह, माता और जन-संपर्क"},mars:{en:"energy, courage, property and bold initiative",hi:"ऊर्जा, साहस, संपत्ति और साहसिक पहल"},mercury:{en:"communication, learning, business and skill-building",hi:"संवाद, अध्ययन, व्यापार और कौशल-निर्माण"},jupiter:{en:"wisdom, growth, teachers, finance and good fortune",hi:"ज्ञान, वृद्धि, गुरुजन, वित्त और सौभाग्य"},venus:{en:"relationships, comforts, arts and financial pleasures",hi:"संबंध, सुख, कला और आर्थिक आनंद"},saturn:{en:"discipline, responsibility, hard work and lasting foundations",hi:"अनुशासन, उत्तरदायित्व, परिश्रम और स्थायी नींव"},rahu:{en:"ambition, foreign matters, technology and unconventional gains",hi:"महत्वाकांक्षा, विदेश-विषय, तकनीक और अपरंपरागत लाभ"},ketu:{en:"introspection, spirituality, research and letting go",hi:"अंतर्मुखता, अध्यात्म, शोध और त्याग"}};
Y.action={excellent:{en:"Launch important initiatives, invest in growth, take opportunities",hi:"महत्वपूर्ण पहल आरंभ करें, वृद्धि में निवेश करें, अवसर लें"},good:{en:"Advance your goals steadily, strengthen key relationships",hi:"लक्ष्यों को स्थिर रूप से आगे बढ़ाएँ, प्रमुख संबंध मज़बूत करें"},mixed:{en:"Focus on strengths, avoid overextension, keep steady routines",hi:"शक्तियों पर ध्यान दें, अति से बचें, स्थिर दिनचर्या रखें"},testing:{en:"Prioritize health and discipline, avoid major risks, be patient",hi:"स्वास्थ्य व अनुशासन को प्राथमिकता दें, बड़े जोखिम टालें, धैर्य रखें"},challenging:{en:"Consolidate, protect resources, practise remedies, avoid big changes",hi:"सुदृढ़ करें, संसाधन सुरक्षित रखें, उपाय करें, बड़े बदलाव टालें"}};
Y.labels={
 title:{en:"10-Year Life Forecast",hi:"10-वर्षीय जीवन भविष्यवाणी"},
 subtitle:{en:"Year by year — dasha, transits and what to do",hi:"वर्ष-दर-वर्ष — दशा, गोचर और क्या करें"},
 overview:{en:"Your Decade at a Glance",hi:"आपका दशक एक दृष्टि में"},
 period:{en:"Running period",hi:"चल रही दशा"},
 theme:{en:"Year theme",hi:"वर्ष का स्वर"},
 domains:{en:"Life Areas This Year",hi:"इस वर्ष जीवन-क्षेत्र"},
 action:{en:"What to do",hi:"क्या करें"},
 jupiter:{en:"Jupiter",hi:"गुरु"}, saturn:{en:"Saturn",hi:"शनि"}, rahu:{en:"Rahu",hi:"राहु"},
 favourable:{en:"Favourable",hi:"अनुकूल"}, attention:{en:"Needs attention",hi:"ध्यान आवश्यक"}, steady:{en:"Steady",hi:"स्थिर"},
 method:{en:"Each year blends your Vimshottari dasha (maha & antar lords) with the house-positions of Jupiter, Saturn and Rahu counted from your Moon — the classical gochara method. Verify placements in your free Kundli report.",hi:"प्रत्येक वर्ष आपकी विंशोत्तरी दशा (महा व अंतर स्वामी) को चंद्र से गिने गुरु, शनि और राहु के भाव-स्थान से जोड़ता है — शास्त्रीय गोचर पद्धति। स्थितियाँ निःशुल्क कुंडली रिपोर्ट में सत्यापित करें।"},
 disclaimer:{en:"Offered in the spirit of tradition for reflection and planning. Your effort and choices shape how each influence unfolds.",hi:"परंपरा की भावना से चिंतन एवं योजना हेतु प्रस्तुत। आपका परिश्रम और निर्णय ही तय करते हैं कि प्रत्येक प्रभाव कैसे प्रकट होता है।"}
};
g.SD_FORECAST=Y;})(typeof window!=='undefined'?window:global);

(function(g){var Y=g.SD_FORECAST;
Y.persona={harvest:{en:"Harvest Year",hi:"फसल वर्ष"},expansion:{en:"Expansion Year",hi:"विस्तार वर्ष"},opportunity:{en:"Opportunity Year",hi:"अवसर वर्ष"},foundation:{en:"Foundation Year",hi:"नींव वर्ष"},planning:{en:"Planning Year",hi:"योजना वर्ष"},consolidation:{en:"Consolidation Year",hi:"सुदृढ़ीकरण वर्ष"},discipline:{en:"Discipline & Growth Year",hi:"अनुशासन-विकास वर्ष"},reflection:{en:"Reflection Year",hi:"चिंतन वर्ष"},momentum:{en:"Momentum Year",hi:"गति वर्ष"},transition:{en:"Transition Year",hi:"संक्रमण वर्ष"}};
Y.spotlightBest={en:"This is one of the brightest years of your decade — a rare alignment where your running period and the great benefics move together in your favour. Say yes to the big opportunities; years like this are meant to be used, not waited out.",hi:"यह आपके दशक के सर्वाधिक उज्ज्वल वर्षों में एक है — एक दुर्लभ संरेखण जहाँ आपकी दशा और महान शुभ ग्रह साथ आपके पक्ष में चलते हैं। बड़े अवसरों को 'हाँ' कहें; ऐसे वर्ष प्रयोग हेतु हैं, प्रतीक्षा हेतु नहीं।"};
Y.spotlightCaution={en:"This is a year to protect rather than expand — several influences test your patience, resources and health at once. This is not misfortune but a Saturn-style checkpoint: guard what you have, avoid big risks, and you cross into brighter years stronger and wiser.",hi:"यह विस्तार नहीं, रक्षा का वर्ष है — अनेक प्रभाव एक साथ आपके धैर्य, संसाधन और स्वास्थ्य की परीक्षा लेते हैं। यह दुर्भाग्य नहीं, शनि-शैली का पड़ाव है: जो है उसकी रक्षा करें, बड़े जोखिम टालें; आप उज्ज्वल वर्षों में अधिक सशक्त और विवेकी होकर प्रवेश करेंगे।"};
Y.opp={career:{en:"Career advancement or promotion",hi:"करियर उन्नति या पदोन्नति"},business:{en:"Starting or expanding a business",hi:"व्यवसाय आरंभ या विस्तार"},property:{en:"Property or vehicle purchase",hi:"संपत्ति या वाहन क्रय"},marriage:{en:"Marriage or deepening relationships",hi:"विवाह या संबंधों में प्रगाढ़ता"},wealth:{en:"Significant financial gains",hi:"महत्वपूर्ण आर्थिक लाभ"},learning:{en:"Higher study or new skills",hi:"उच्च अध्ययन या नए कौशल"},travel:{en:"Beneficial travel or relocation",hi:"लाभकारी यात्रा या स्थानांतरण"}};
Y.risk={loans:{en:"Taking large loans or debts",hi:"बड़े ऋण लेना"},speculation:{en:"Speculation and risky investments",hi:"सट्टा एवं जोखिमपूर्ण निवेश"},burnout:{en:"Overwork and burnout",hi:"अति-श्रम एवं थकान"},health:{en:"Neglecting health",hi:"स्वास्थ्य की उपेक्षा"},conflict:{en:"Major disputes or conflicts",hi:"बड़े विवाद या टकराव"},overconfidence:{en:"Overconfidence in decisions",hi:"निर्णयों में अति-आत्मविश्वास"}};
Y.spotLabels={
 bright:{en:"✨ Spotlight Year",hi:"✨ विशेष वर्ष"},
 caution:{en:"⚠️ Caution Year",hi:"⚠️ सतर्कता वर्ष"},
 opportunities:{en:"Big Opportunities",hi:"बड़े अवसर"},
 avoid:{en:"Things to Avoid",hi:"क्या टालें"},
 strategy:{en:"Best Strategy",hi:"श्रेष्ठ रणनीति"},
 domains:{en:"Life Areas in Detail",hi:"जीवन-क्षेत्र विस्तार से"},
 career:{en:"Career",hi:"करियर"}, money:{en:"Money",hi:"धन"}, marriage:{en:"Relationships",hi:"संबंध"},
 health:{en:"Health",hi:"स्वास्थ्य"}, travel:{en:"Travel",hi:"यात्रा"}, invest:{en:"Investments",hi:"निवेश"}
};
})(typeof window!=='undefined'?window:global);

(function(g){var Y=g.SD_FORECAST;
Y.houseArea={1:{en:"self, health and personal direction",hi:"स्वयं, स्वास्थ्य एवं व्यक्तिगत दिशा"},2:{en:"wealth, family and speech",hi:"धन, परिवार एवं वाणी"},3:{en:"courage, communication and siblings",hi:"साहस, संवाद एवं सहोदर"},4:{en:"home, property, mother and inner peace",hi:"गृह, संपत्ति, माता एवं मन-शांति"},5:{en:"creativity, children, learning and romance",hi:"सृजन, संतान, विद्या एवं प्रणय"},6:{en:"work, service, health and overcoming rivals",hi:"कार्य, सेवा, स्वास्थ्य एवं शत्रु-विजय"},7:{en:"partnerships, marriage and public dealings",hi:"साझेदारी, विवाह एवं जन-व्यवहार"},8:{en:"transformation, shared resources and research",hi:"रूपांतरण, साझा संसाधन एवं शोध"},9:{en:"fortune, higher learning, dharma and travel",hi:"भाग्य, उच्च विद्या, धर्म एवं यात्रा"},10:{en:"career, status and public achievement",hi:"करियर, प्रतिष्ठा एवं सार्वजनिक उपलब्धि"},11:{en:"gains, income, networks and fulfilled wishes",hi:"लाभ, आय, संपर्क एवं कामना-पूर्ति"},12:{en:"expenses, foreign matters, spirituality and rest",hi:"व्यय, विदेश-विषय, अध्यात्म एवं विश्राम"}};
Y.themeJoin={
 strong:{en:"strongly activating",hi:"प्रबलता से सक्रिय करते हुए"},
 normal:{en:"bringing focus to",hi:"ध्यान केंद्रित करते हुए"},
 weak:{en:"asking patient effort in",hi:"धैर्यपूर्ण प्रयास माँगते हुए"}
};
})(typeof window!=='undefined'?window:global);
