// SHUBH DIN — Love & Relationship Report Content (EN+HI)
(function(g){var LV={};
LV.loveStyle={fire:{en:"You love the way a flame loves — brightly, boldly, all at once. When your heart is drawn to someone, there is no half-measure: you pursue, you adore, you burn beautifully. Yours is a love that feels like being chosen by the sun. Give that fire a worthy hearth, and it will warm a lifetime.",hi:"आप वैसे प्रेम करते हैं जैसे अग्नि प्रेम करती है — उज्ज्वल, निर्भीक, एक साथ पूर्ण। जब हृदय किसी की ओर खिंचता है, तब आधा-अधूरा कुछ नहीं होता: आप पाते हैं, पूजते हैं, सुंदरता से जलते हैं। आपका प्रेम सूर्य द्वारा चुने जाने-सा अनुभव देता है। इस अग्नि को योग्य आश्रय दें, यह जीवन भर उष्मा देगी।"},earth:{en:"You love the way the earth loves — patiently, faithfully, and for keeps. You are not swept away by fleeting sparks; you build something that lasts, stone by tender stone. To be loved by you is to feel safe, cherished and quietly certain. Yours is the rarest gift of all: a love that stays.",hi:"आप वैसे प्रेम करते हैं जैसे धरती प्रेम करती है — धैर्यपूर्वक, निष्ठा से, सदा के लिए। क्षणिक चिंगारियाँ आपको नहीं बहातीं; आप कुछ ऐसा रचते हैं जो टिके, कोमल पत्थर-दर-पत्थर। आपके प्रेम में सुरक्षा, स्नेह और शांत निश्चय का अनुभव है। आपका प्रेम सबसे दुर्लभ उपहार है: वह प्रेम जो ठहरता है।"},air:{en:"You love the way the wind loves — through words, laughter and meeting of minds. For you, the deepest romance begins as conversation that never wants to end. You need a partner who is also a friend, a mind that dances with yours. When you find someone who truly gets you, the connection is electric and endless.",hi:"आप वैसे प्रेम करते हैं जैसे पवन प्रेम करती है — शब्दों, हँसी और मनों के मिलन से। आपके लिए गहनतम प्रणय उस संवाद से आरंभ होता है जो कभी समाप्त नहीं होना चाहता। आपको ऐसा साथी चाहिए जो मित्र भी हो, एक मन जो आपके संग नाचे। जब कोई सचमुच आपको समझता है, तब वह जुड़ाव विद्युत-सा और अनंत होता है।"},water:{en:"You love the way the ocean loves — deeply, intuitively, with your whole soul. You feel everything, and when you give your heart, you give its very depths. You sense what your beloved needs before they speak it. Yours is a tender, devoted, romantic love — and the right person will treasure how profoundly you feel.",hi:"आप वैसे प्रेम करते हैं जैसे सागर प्रेम करता है — गहराई से, सहजबोध से, पूरी आत्मा से। आप सब कुछ अनुभव करते हैं, और जब हृदय देते हैं, तब उसकी गहराइयाँ दे देते हैं। प्रिय की आवश्यकता उनके कहने से पहले भाँप लेते हैं। आपका प्रेम कोमल, समर्पित, रोमांटिक है — और सही व्यक्ति इस गहन अनुभूति को अनमोल मानेगा।"}};
LV.partner={fire:{en:"Your heart is destined to be lit by a partner of fire — someone spirited, confident and radiant, who walks into a room and changes its temperature. This is a soul with courage and warmth, who will inspire you and match your intensity. Look for the one whose presence feels like sunrise.",hi:"आपका हृदय अग्नि-स्वभाव के साथी से प्रज्वलित होने को है — कोई उत्साही, आत्मविश्वासी और तेजस्वी, जो कक्ष में प्रवेश करते ही उसका ताप बदल दे। यह साहस और उष्मा वाली आत्मा है, जो आपको प्रेरित करेगी और आपकी तीव्रता से मेल खाएगी। उसे खोजें जिसकी उपस्थिति सूर्योदय-सी लगे।"},earth:{en:"The one who is meant for you carries the steadiness of earth — grounded, dependable and beautifully real. This is a partner who shows love through devotion and presence rather than grand words; who builds a home with you, not just a romance. Look for the one who feels like coming home.",hi:"जो आपके लिए बना है, वह धरती की स्थिरता रखता है — व्यावहारिक, विश्वसनीय और सुंदरता से वास्तविक। यह साथी भव्य शब्दों से नहीं, समर्पण और उपस्थिति से प्रेम दर्शाता है; जो आपके संग केवल प्रणय नहीं, घर बनाता है। उसे खोजें जो घर लौटने-सा लगे।"},air:{en:"Your other half is a spirit of air — bright, witty and endlessly interesting, a mind that will enchant yours. This is someone you can talk to for hours, who makes you laugh and think in the same breath. Chemistry, for you, is intellectual before it is anything else. Look for the one whose words feel like music.",hi:"आपका दूसरा आधा पवन-स्वभाव की आत्मा है — प्रखर, विनोदी और अनंत रोचक, एक मन जो आपके मन को मोहित करे। यह कोई ऐसा है जिससे आप घंटों बात कर सकें, जो एक ही साँस में हँसाए और सोचने पर विवश करे। आपके लिए आकर्षण सबसे पहले बौद्धिक होता है। उसे खोजें जिसके शब्द संगीत-से लगें।"},water:{en:"Destiny is guiding you toward a soul of water — deep, feeling and gently intuitive, someone who loves with tenderness and understands without asking. This is a partner who will hold your heart safely and meet your emotional world with their own. Look for the one whose eyes feel like they already know you.",hi:"भाग्य आपको जल-स्वभाव की आत्मा की ओर ले जा रहा है — गहरी, संवेदनशील और कोमल सहजबोध वाली, कोई जो कोमलता से प्रेम करे और बिना पूछे समझे। यह साथी आपके हृदय को सुरक्षित थामेगा और आपके भाव-जगत से अपने भाव-जगत से मिलेगा। उसे खोजें जिसकी आँखें पहले से आपको जानती-सी लगें।"}};
LV.scoreBand={radiant:{t_en:"Your chart glows with the promise of love",t_hi:"आपकी कुंडली प्रेम के वचन से दमकती है",en:"The houses of romance and partnership are richly blessed in your chart — love is not a question of if, but of when and how beautifully. You are made for deep connection, and the stars have written warmth into your story. Trust your heart; it is well-guided.",hi:"आपकी कुंडली में प्रणय और साझेदारी के भाव समृद्ध रूप से आशीर्वादित हैं — प्रेम 'यदि' का नहीं, 'कब और कितनी सुंदरता से' का प्रश्न है। आप गहन जुड़ाव के लिए बने हैं, और तारों ने आपकी कथा में उष्मा लिखी है। हृदय पर भरोसा रखें; वह सुमार्गित है।"},warm:{t_en:"Love flows warmly through your chart",t_hi:"प्रेम आपकी कुंडली में उष्मा से बहता है",en:"Your chart carries a warm and favourable current for love — genuine connection comes to you, especially in the blessed periods ahead. Relationships bring you growth and joy. With an open and patient heart, love finds its way to you beautifully.",hi:"आपकी कुंडली प्रेम हेतु उष्ण और अनुकूल धारा रखती है — सच्चा जुड़ाव आपके पास आता है, विशेषकर आगामी शुभ अवधियों में। संबंध आपको विकास और आनंद देते हैं। खुले और धैर्यवान हृदय से, प्रेम सुंदरता से आप तक पहुँचता है।"},tender:{t_en:"Your love story unfolds in its own gentle time",t_hi:"आपकी प्रेम-कथा अपने कोमल समय में खुलती है",en:"Love, for you, ripens like fruit in its season — it asks for a little patience, and rewards it richly. The tender areas of your chart are an invitation to self-love and readiness, so that when the right soul arrives, you are whole to receive them. The blessed windows ahead hold real promise.",hi:"आपके लिए प्रेम ऋतु के फल-सा पकता है — यह थोड़ा धैर्य माँगता है, और उसे भरपूर फल देता है। आपकी कुंडली के कोमल क्षेत्र आत्म-प्रेम और तत्परता का निमंत्रण हैं, ताकि जब सही आत्मा आए, आप उसे पाने को पूर्ण हों। आगे की शुभ अवधियाँ सच्चा वचन रखती हैं।"}};
LV.passion={high:{en:"There is a magnetic, passionate fire in your romantic nature — attraction comes alive powerfully when your heart is engaged.",hi:"आपकी प्रणय-प्रकृति में चुंबकीय, उत्कट अग्नि है — जब हृदय जुड़ता है, आकर्षण प्रबलता से जाग उठता है।"},balanced:{en:"Your passion runs warm and steady — a beautiful balance of desire and tenderness that makes love feel both exciting and safe.",hi:"आपकी उत्कटता उष्ण और स्थिर बहती है — इच्छा और कोमलता का सुंदर संतुलन जो प्रेम को रोमांचक और सुरक्षित दोनों बनाता है।"}};
LV.elements={
 fire:{en:"Fire",hi:"अग्नि"}, earth:{en:"Earth",hi:"पृथ्वी"}, air:{en:"Air",hi:"वायु"}, water:{en:"Water",hi:"जल"}
};
LV.labels={
 title:{en:"Your Love Story",hi:"आपकी प्रेम कथा"},
 subtitle:{en:"How you love, who you seek, and when love blooms",hi:"आप कैसे प्रेम करते हैं, किसे खोजते हैं, और प्रेम कब खिलता है"},
 loveLang:{en:"Your Love Language",hi:"आपकी प्रेम भाषा"},
 yourHeart:{en:"The Nature of Your Heart",hi:"आपके हृदय का स्वभाव"},
 idealPartner:{en:"The One You're Meant to Find",hi:"जिसे आप पाने को हैं"},
 chemistry:{en:"Your Romantic Chemistry",hi:"आपका प्रणय रसायन"},
 passion:{en:"Passion",hi:"उत्कटता"}, romance:{en:"Romance",hi:"प्रणय"}, commitment:{en:"Commitment",hi:"प्रतिबद्धता"},
 whenLove:{en:"When Love Blooms",hi:"प्रेम कब खिलता है"},
 whenLoveIntro:{en:"The stars mark certain seasons when love flowers most readily for you. In these blessed windows, hearts open, meetings feel fated, and existing bonds deepen:",hi:"तारे कुछ ऋतुएँ अंकित करते हैं जब प्रेम आपके लिए सर्वाधिक सहजता से खिलता है। इन शुभ अवधियों में हृदय खुलते हैं, भेंट नियत लगती है, और विद्यमान बंधन प्रगाढ़ होते हैं:"},
 whyWin:{en:"Why this season",hi:"यह ऋतु क्यों"},
 remedies:{en:"To Invite Love's Grace",hi:"प्रेम की कृपा हेतु"},
 venusStrength:{en:"Venus, the planet of love, in your chart",hi:"प्रेम-ग्रह शुक्र, आपकी कुंडली में"},
 method:{en:"Drawn from Venus (the planet of love), your Moon (the heart), and the 5th and 7th houses of romance and union in your chart. Verify against your free Kundli report.",hi:"शुक्र (प्रेम-ग्रह), आपके चंद्र (हृदय), और आपकी कुंडली के प्रणय-मिलन के 5वें व 7वें भाव से लिया गया। निःशुल्क कुंडली रिपोर्ट से सत्यापित करें।"},
 disclaimer:{en:"Offered in the spirit of tradition and wonder. The stars incline; they do not compel. Your open heart writes the truest love story of all.",hi:"परंपरा और विस्मय की भावना से प्रस्तुत। तारे झुकाव देते हैं; बाध्य नहीं करते। आपका खुला हृदय ही सबसे सच्ची प्रेम-कथा लिखता है।"}
};
g.SD_LOVE=LV;})(typeof window!=='undefined'?window:global);
