// SHUBH DIN — Marriage Report Content (EN+HI)
(function(g){var M={};
M.domains={
 emotional:{t_en:"Emotional Compatibility",t_hi:"भावनात्मक अनुकूलता",strong:{en:"Your Moons speak the same language — feelings are understood here often before they are spoken. This bond can weather storms because the hearts genuinely translate each other.",hi:"आपके चंद्रमा एक ही भाषा बोलते हैं — भावनाएँ यहाँ प्रायः कहे जाने से पहले समझ ली जाती हैं। यह बंधन तूफ़ान झेल सकता है क्योंकि हृदय सचमुच एक-दूसरे का अनुवाद करते हैं।"},avg:{en:"Your emotional natures differ enough to keep learning alive — with listening, each becomes the other's missing vocabulary. Give feelings words, and closeness grows steadily.",hi:"आपकी भाव-प्रकृतियाँ इतनी भिन्न हैं कि सीखना जीवित रहे — सुनने से, प्रत्येक दूसरे की अधूरी शब्दावली बन जाता है। भावनाओं को शब्द दीजिए, निकटता क्रमशः बढ़ेगी।"},care:{en:"Your Moons feel life differently — one may need words where the other needs silence. This asks for patience, not alarm: agree on small rituals of reassurance, and the difference becomes depth.",hi:"आपके चंद्रमा जीवन को भिन्न ढंग से अनुभव करते हैं — एक को शब्द चाहिए तो दूसरे को मौन। यह चिंता नहीं, धैर्य माँगता है: आश्वासन की छोटी रीतियाँ तय कीजिए, भिन्नता गहराई बन जाएगी।"}},
 communication:{t_en:"Communication & Understanding",t_hi:"संवाद एवं समझ",strong:{en:"Mercury blesses your conversations — humour, planning and problem-solving flow easily between you. Decisions made talking together will usually be your best ones.",hi:"बुध आपके संवादों को आशीर्वाद देते हैं — हास्य, योजना और समाधान आपके बीच सहज बहते हैं। साथ बैठकर लिए निर्णय प्रायः आपके श्रेष्ठतम होंगे।"},avg:{en:"Your thinking styles are complementary rather than identical — one sees the forest, the other the trees. Summarize decisions aloud and confirm; misunderstandings then rarely survive a day.",hi:"आपकी विचार-शैलियाँ समान नहीं, पूरक हैं — एक वन देखता है, दूसरा वृक्ष। निर्णय बोलकर दोहराएँ और पुष्टि करें; ग़लतफ़हमियाँ फिर एक दिन भी नहीं टिकतीं।"},care:{en:"Mercury asks you both to work at translation — assumptions are this pairing's only enemy. Write important things down, ask twice, tease gently: the effort itself becomes intimacy.",hi:"बुध आप दोनों से अनुवाद का श्रम माँगते हैं — इस जोड़ी का एकमात्र शत्रु 'मान लेना' है। महत्वपूर्ण बातें लिखें, दो बार पूछें, सस्नेह हँसें: यही प्रयास आत्मीयता बन जाता है।"}},
 romance:{t_en:"Romance & Attraction",t_hi:"प्रणय एवं आकर्षण",strong:{en:"Venus and Mars dance well between your charts — attraction here is natural and renewing. Keep courting each other after marriage; this pairing rewards it richly.",hi:"आपकी कुंडलियों के बीच शुक्र-मंगल का नृत्य सधा हुआ है — आकर्षण यहाँ स्वाभाविक और नित-नूतन है। विवाह के बाद भी एक-दूसरे को रिझाते रहिए; यह जोड़ी इसका भरपूर फल देती है।"},avg:{en:"Attraction is present and steady, glowing brighter with shared experiences than grand gestures. Invest in small daily affections — they are this pairing's true currency.",hi:"आकर्षण उपस्थित और स्थिर है, जो भव्य प्रदर्शनों से अधिक साझा अनुभवों से चमकता है। छोटे नित्य स्नेह में निवेश कीजिए — वही इस जोड़ी की सच्ची मुद्रा है।"},care:{en:"The Venus–Mars weave asks for conscious tending — romance here is a garden, not a wildfire. Schedule beauty into the calendar and protect couple-time; tended, this garden blooms for decades.",hi:"शुक्र-मंगल का ताना-बाना सचेत देखभाल माँगता है — यहाँ प्रणय जंगल की आग नहीं, उपवन है। सौंदर्य को समय दीजिए और दांपत्य-क्षण सुरक्षित रखिए; सिंचित यह उपवन दशकों खिलता है।"}},
 family:{t_en:"Family Adjustment",t_hi:"पारिवारिक सामंजस्य",strong:{en:"Your temperaments (Gana) and sign-relation (Bhakoot) support easy blending of families — festivals, in-laws and shared duties should find natural rhythm around you two.",hi:"आपके स्वभाव (गण) और राशि-संबंध (भकूट) परिवारों के सहज मिलन का समर्थन करते हैं — पर्व, ससुराल और साझा कर्तव्य आपके चारों ओर स्वाभाविक लय पा लेंगे।"},avg:{en:"Family blending will be mostly smooth with occasional tuning — agree early on boundaries and festivals, and honour both houses equally; harmony then becomes habit.",hi:"पारिवारिक मिलन प्रायः सहज रहेगा, कभी-कभी संतुलन माँगेगा — सीमाएँ और पर्व पहले तय करें, दोनों कुलों का समान मान रखें; सामंजस्य फिर स्वभाव बन जाता है।"},care:{en:"Family adjustment is this match's practice-ground — differing temperaments can pull toward respective homes. A united front, decided privately and spoken jointly, dissolves most friction before it starts.",hi:"पारिवारिक सामंजस्य इस संबंध की साधना-भूमि है — भिन्न स्वभाव अपने-अपने घरों की ओर खींच सकते हैं। एकांत में तय और साथ में कहा गया साझा मत अधिकांश घर्षण को जन्म से पहले घोल देता है।"}},
 finance:{t_en:"Financial Compatibility",t_hi:"आर्थिक अनुकूलता",strong:{en:"Your wealth-lords cooperate — earning, saving and spending instincts align well. Joint financial goals set early can compound into genuine prosperity together.",hi:"आपके धनेश सहयोगी हैं — अर्जन, बचत और व्यय की प्रवृत्तियाँ मेल खाती हैं। शीघ्र तय किए साझा आर्थिक लक्ष्य मिलकर सच्ची समृद्धि में चक्रवृद्धि हो सकते हैं।"},avg:{en:"Money styles differ mildly — likely one saves where the other invests in experiences. A simple shared budget with personal allowances keeps both natures honoured and the treasury growing.",hi:"धन-शैलियाँ हल्की भिन्न हैं — संभवतः एक बचाता है, दूसरा अनुभवों में लगाता है। निजी छूट सहित सरल साझा बजट दोनों प्रकृतियों का मान रखता है और कोष बढ़ाता है।"},care:{en:"Finances ask for structure in this pairing — unspoken money expectations are the risk, not money itself. Decide contributions, savings and family support openly each year; clarity here is love made practical.",hi:"इस जोड़ी में धन व्यवस्था माँगता है — जोखिम धन नहीं, अनकही अपेक्षाएँ हैं। योगदान, बचत और पारिवारिक सहयोग प्रतिवर्ष खुलकर तय करें; यहाँ स्पष्टता ही व्यावहारिक प्रेम है।"}},
 children:{t_en:"Children & Legacy",t_hi:"संतान एवं वंश",strong:{en:"Both fifth houses and the Saptamsa charts lean supportive — the blessing of children and joy through them is classically indicated for this union.",hi:"दोनों पंचम भाव और सप्तांश चक्र अनुकूल झुकाव रखते हैं — इस संबंध हेतु संतान-सुख और उनसे आनंद के शास्त्रीय संकेत हैं।"},avg:{en:"Children prospects are steady — timing matters more than possibility. The favourable windows chapter of this report highlights the classically supported periods.",hi:"संतान-योग स्थिर हैं — संभावना से अधिक महत्व समय का है। इस रिपोर्ट का शुभ-खिड़की अध्याय शास्त्र-समर्थित अवधियाँ दर्शाता है।"},care:{en:"The fifth-house weave asks for patience and, per tradition, Santan Gopal upasana — many revered family lines began exactly so. Medical wisdom and mantra walk well together; neither replaces the other.",hi:"पंचम भाव का ताना-बाना धैर्य और परंपरानुसार संतान-गोपाल उपासना माँगता है — अनेक पूज्य वंश ऐसे ही आरंभ हुए। चिकित्सा-विवेक और मंत्र साथ-साथ चलते हैं; कोई किसी का विकल्प नहीं।"}},
};
M.koota={
 "Varna":{en:"Spiritual ego compatibility — who naturally leads in matters of principle.",hi:"आध्यात्मिक अहं-अनुकूलता — सिद्धांत के विषयों में स्वाभाविक अग्रता किसकी।"},
 "Vashya":{en:"Mutual influence — how naturally you two sway each other.",hi:"परस्पर प्रभाव — आप दोनों एक-दूसरे को कितनी सहजता से प्रभावित करते हैं।"},
 "Tara":{en:"Destiny-star harmony — health and fortune flowing between the birth stars.",hi:"तारा-अनुकूलता — जन्म नक्षत्रों के बीच बहता स्वास्थ्य और सौभाग्य।"},
 "Yoni":{en:"Instinctive and physical harmony of natures.",hi:"प्रकृतियों की सहज एवं शारीरिक अनुकूलता।"},
 "Graha Maitri":{en:"Friendship of the Moon-sign lords — the minds' natural alliance.",hi:"राश्याधिपतियों की मैत्री — मनों का स्वाभाविक गठबंधन।"},
 "Gana":{en:"Temperament class (Deva/Manushya/Rakshasa) — daily-life energy match.",hi:"गण (देव/मनुष्य/राक्षस) — दैनिक जीवन-ऊर्जा का मेल।"},
 "Bhakoot":{en:"Moon-sign distance — emotional and material life-rhythm alignment.",hi:"राशियों की परस्पर दूरी — भाव एवं भौतिक जीवन-लय का संरेखण।"},
 "Nadi":{en:"Constitutional stream — classical health-of-progeny consideration.",hi:"नाड़ी — संतति-स्वास्थ्य का शास्त्रीय विचार।"},
};
M.verdict={
 excellent:{en:"An excellent union by classical measure — the charts embrace each other. Proceed with joy and gratitude.",hi:"शास्त्रीय मापदंड से उत्तम संबंध — कुंडलियाँ एक-दूसरे का आलिंगन करती हैं। हर्ष और कृतज्ञता से आगे बढ़ें।"},
 verygood:{en:"A very good match — strengths clearly outweigh the points needing care. With the noted attentions, this union is well blessed.",hi:"अति उत्तम मिलान — शक्तियाँ ध्यान-योग्य बिंदुओं से स्पष्ट भारी हैं। उल्लिखित सावधानियों सहित यह संबंध सुआशीर्वादित है।"},
 acceptable:{en:"An acceptable match with real foundations — the effective score after cancellations shows workable harmony. The care-points below are a to-do list, not a verdict.",hi:"वास्तविक आधार वाला स्वीकार्य मिलान — परिहारों के बाद प्रभावी अंक कार्यसाध्य सामंजस्य दिखाते हैं। नीचे के ध्यान-बिंदु कार्य-सूची हैं, निर्णय नहीं।"},
 care:{en:"This match asks for careful consideration — tradition advises elder counsel, the listed remedies, and honest conversation between families before proceeding.",hi:"यह मिलान सावधान विचार माँगता है — परंपरा गुरुजन-परामर्श, उल्लिखित उपाय और परिवारों के बीच निष्कपट संवाद की सलाह देती है।"},
};
M.labels={
 title:{en:"Marriage Compatibility Report",hi:"विवाह अनुकूलता रिपोर्ट"},
 couple:{en:"Prepared for",hi:"हेतु प्रस्तुत"},
 dash:{en:"Compatibility Dashboard",hi:"अनुकूलता डैशबोर्ड"},
 guna:{en:"Guna Milan — with Cancellation Analysis",hi:"गुण मिलान — परिहार विश्लेषण सहित"},
 raw:{en:"Raw score",hi:"मूल अंक"}, eff:{en:"Effective score (after classical cancellations)",hi:"प्रभावी अंक (शास्त्रीय परिहारों के बाद)"},
 cancelled:{en:"CANCELLED",hi:"परिहार सिद्ध"}, stands:{en:"needs care",hi:"ध्यान आवश्यक"},
 manglik:{en:"Mangal Dosha — Two-Chart Analysis",hi:"मंगल दोष — द्वि-कुंडली विश्लेषण"},
 windows:{en:"Favourable Marriage Windows",hi:"विवाह हेतु शुभ अवधियाँ"},
 whyWin:{en:"Why this window",hi:"यह अवधि क्यों"},
 strengths:{en:"Major Strengths of this Union",hi:"इस संबंध की प्रमुख शक्तियाँ"},
 carePts:{en:"Points Needing Care",hi:"ध्यान-योग्य बिंदु"},
 remedies:{en:"Remedies as Sadhana",hi:"उपाय — साधना रूप में"},
 method:{en:"Every score derives from the computed tables in this report — koota points, lord friendships, dignities and dashas. Nothing is invented.",hi:"प्रत्येक अंक इसी रिपोर्ट की गणना-सारणियों से व्युत्पन्न है — कूट अंक, ग्रह-मैत्री, गरिमा और दशाएँ। कुछ भी मनगढ़ंत नहीं।"},
 disclaimer:{en:"Offered in the spirit of tradition for reflection. Marriage is a decision of hearts and families — your judgement remains supreme.",hi:"परंपरा की भावना से चिंतन हेतु प्रस्तुत। विवाह हृदयों और परिवारों का निर्णय है — आपका विवेक ही सर्वोपरि है।"}
};
g.SD_MARRIAGE=M;})(typeof window!=='undefined'?window:global);
