// SHUBH DIN — Kundli Report Content Library (v1, EN + HI)
// Text blocks keyed to engine outputs. Written per the K8 psychology playbook:
// strengths-first, warm second person, hedged cautions always paired with sadhana.
(function (global) {
  'use strict';
  var C = {};

  // ---- Birth Nakshatra personality (27) ----
  C.nakshatra = [
  { en: "Born under Ashvini, you carry the energy of new beginnings — quick to act, quick to heal, and quick to help. People notice your youthful enthusiasm and your gift for getting things started. Practise patience with slower souls; finishing what you begin multiplies your natural brilliance.",
    hi: "अश्विनी नक्षत्र में जन्मे आप नई शुरुआत की ऊर्जा लेकर आए हैं — तुरंत कार्य करने वाले, शीघ्र स्वस्थ होने वाले और सहायता के लिए सदा तत्पर। आपकी युवा-सी स्फूर्ति सबका ध्यान खींचती है। धैर्य का अभ्यास और आरंभ किए कार्य को पूर्ण करना आपकी प्रतिभा को कई गुना कर देता है।" },
  { en: "Bharani gives you rare inner strength — you can carry responsibilities that would exhaust others, and you transform every hardship into wisdom. Loyalty runs deep in you. Guard against taking on too much silently; sharing your burden is strength, not weakness.",
    hi: "भरणी आपको दुर्लभ आंतरिक शक्ति देती है — आप वे उत्तरदायित्व सहज उठा लेते हैं जो औरों को थका दें, और हर कठिनाई को अनुभव में बदल देते हैं। निष्ठा आपके स्वभाव में है। सब कुछ अकेले चुपचाप उठाने से बचें; अपनों से बाँट लेना भी शक्ति ही है।" },
  { en: "Krittika blesses you with a sharp, purifying intellect — you see through pretence instantly and speak truth with courage. You set high standards and inspire others to rise. Let warmth soften your fire; your honesty lands best when wrapped in kindness.",
    hi: "कृत्तिका आपको तीक्ष्ण, शुद्ध करने वाली बुद्धि देती है — आप दिखावे को तुरंत पहचान लेते हैं और साहस से सत्य कहते हैं। आपके ऊँचे मापदंड औरों को भी ऊपर उठाते हैं। अपनी अग्नि में स्नेह मिलाइए; करुणा के साथ कहा गया सत्य सबसे गहरा उतरता है।" },
  { en: "Rohini makes you naturally magnetic — creative, steady, and deeply appreciative of beauty and comfort. Things grow under your care: family, savings, gardens, relationships. Watch attachment to comfort; a little discipline keeps your abundance flowing.",
    hi: "रोहिणी आपको सहज आकर्षण देती है — रचनात्मक, स्थिर और सौंदर्य के सच्चे पारखी। आपके स्पर्श से चीज़ें फलती-फूलती हैं: परिवार, बचत, संबंध। सुख-सुविधा से अधिक मोह से सावधान रहें; थोड़ा संयम आपकी समृद्धि को सदा प्रवाहित रखता है।" },
  { en: "Mrigashira gives you a seeker's heart — curious, gentle, always searching for something finer. You learn quickly and converse beautifully. Restlessness is your only shadow; when you commit to one path deeply, you find the very treasure you were seeking.",
    hi: "मृगशिरा आपको खोजी हृदय देता है — जिज्ञासु, सौम्य, सदा किसी श्रेष्ठ वस्तु की तलाश में। आप शीघ्र सीखते हैं और मधुर संवाद करते हैं। चंचलता ही एकमात्र छाया है; जब आप एक मार्ग पर गहराई से टिकते हैं, वही खज़ाना मिल जाता है जिसकी खोज थी।" },
  { en: "Ardra grants you intensity and intelligence that thrive in storms — you handle crises that overwhelm others and emerge renewed. Your empathy for suffering is profound. Channel the storm through steady routines; calm waters let your genius shine longest.",
    hi: "आर्द्रा आपको वह तीव्रता और बुद्धि देती है जो तूफ़ानों में निखरती है — आप उन संकटों को संभाल लेते हैं जो औरों को तोड़ दें, और नए होकर निकलते हैं। दुख के प्रति आपकी संवेदना गहरी है। नियमित दिनचर्या से इस ऊर्जा को दिशा दें; शांत जल में आपकी प्रतिभा सबसे देर तक चमकती है।" },
  { en: "Punarvasu is the star of return and renewal — no setback keeps you down for long. You rebuild, restore, and bring hope wherever you go. Generous and philosophical, you gather goodwill everywhere. Trust your comeback power; it is your life's signature.",
    hi: "पुनर्वसु पुनरागमन और नवीनीकरण का नक्षत्र है — कोई भी विफलता आपको अधिक समय तक रोक नहीं पाती। आप फिर बनाते हैं, फिर सँवारते हैं और जहाँ जाते हैं आशा ले जाते हैं। उदार और चिंतनशील स्वभाव सबका स्नेह जीतता है। अपनी वापसी की शक्ति पर विश्वास रखें; यही आपके जीवन की पहचान है।" },
  { en: "Pushya, the most nourishing nakshatra, makes you a natural protector — dependable, dutiful, and quietly powerful. People instinctively trust you with what they value most. Remember to nourish yourself too; your care multiplies when your own cup is full.",
    hi: "पुष्य, सबसे पोषक नक्षत्र, आपको स्वाभाविक संरक्षक बनाता है — विश्वसनीय, कर्तव्यनिष्ठ और शांत शक्ति से भरा। लोग सहज ही अपनी प्रिय वस्तुएँ आपको सौंप देते हैं। स्वयं का पोषण भी करें; जब आपका पात्र भरा रहता है, आपकी सेवा कई गुना फलती है।" },
  { en: "Ashlesha gives you penetrating insight — you read people and situations at a depth few possess, and your focus, once locked, is unbreakable. Use this power to heal and guide. Release grudges quickly; forgiveness keeps your remarkable mind luminous.",
    hi: "आश्लेषा आपको भेदक अंतर्दृष्टि देती है — आप व्यक्तियों और परिस्थितियों को उस गहराई तक पढ़ लेते हैं जहाँ कम ही पहुँचते हैं, और एक बार लगी एकाग्रता अटूट होती है। इस शक्ति से मार्गदर्शन कीजिए। मन की गाँठें शीघ्र खोल दें; क्षमा आपके विलक्षण मन को उजला रखती है।" },
  { en: "Magha connects you to noble lineage and leadership — dignity comes naturally, and you honour traditions while carrying real authority. Others look to you in important moments. Lead with humility and gratitude to elders; that is where your throne truly stands.",
    hi: "मघा आपको कुल-गौरव और नेतृत्व से जोड़ती है — गरिमा आपमें सहज है, आप परंपराओं का सम्मान करते हुए वास्तविक अधिकार धारण करते हैं। महत्वपूर्ण क्षणों में लोग आपकी ओर देखते हैं। विनम्रता और पितरों-बड़ों के प्रति कृतज्ञता के साथ नेतृत्व करें; आपका सिंहासन वहीं स्थिर है।" },
  { en: "Purva Phalguni fills you with warmth, charm, and the art of enjoying life — you create joy around you and love generously. Creativity and relationships flourish in your presence. Balance pleasure with purpose; your charisma achieves wonders when pointed at a goal.",
    hi: "पूर्वा फाल्गुनी आपको उष्णता, आकर्षण और जीवन का आनंद लेने की कला देती है — आप अपने चारों ओर उत्सव रचते हैं और खुले हृदय से प्रेम करते हैं। रचनात्मकता और संबंध आपके संग खिलते हैं। आनंद के साथ उद्देश्य जोड़िए; लक्ष्य की ओर मुड़ा आपका आकर्षण चमत्कार करता है।" },
  { en: "Uttara Phalguni gives you the gift of reliable friendship and honourable dealing — people build their plans on your word, and your generosity uplifts many. Partnerships prosper with you. Keep clear boundaries; helping wisely serves more than helping endlessly.",
    hi: "उत्तरा फाल्गुनी आपको विश्वसनीय मित्रता और सम्मानपूर्ण व्यवहार का वरदान देती है — लोग आपके वचन पर योजनाएँ बनाते हैं, आपकी उदारता अनेकों को ऊपर उठाती है। साझेदारियाँ आपके साथ फलती हैं। सीमाएँ स्पष्ट रखें; विवेकपूर्ण सहायता अनंत सहायता से अधिक फलदायी है।" },
  { en: "Hasta places skill directly in your hands — craftsmanship, healing, precise work, and clever wit all come naturally. What you touch improves. Trust your hands-on judgment over second-hand opinions, and keep a light heart; your humour is medicine for many.",
    hi: "हस्त नक्षत्र कौशल सीधे आपके हाथों में रखता है — शिल्प, सेवा-सुश्रूषा, सूक्ष्म कार्य और चतुर वाणी आपमें सहज है। जिसे आप छूते हैं वह निखर जाता है। दूसरों की सुनी-सुनाई राय से अधिक अपने हाथ के अनुभव पर भरोसा रखें, और मन हल्का रखें; आपका हास्य कई हृदयों की औषधि है।" },
  { en: "Chitra makes you a born designer of life — you see the finished masterpiece where others see raw material, and you have the courage to build it. Style, structure, and brilliance mark your work. Accept imperfect first drafts; masterpieces are polished, not born.",
    hi: "चित्रा आपको जीवन का जन्मजात शिल्पी बनाती है — जहाँ अन्य कच्चा माल देखते हैं, आप बनी हुई उत्कृष्ट कृति देख लेते हैं, और उसे गढ़ने का साहस रखते हैं। शैली, संरचना और तेज आपके कार्य की पहचान है। पहले प्रयास की अपूर्णता स्वीकारें; कृतियाँ जन्म से नहीं, तराशने से महान बनती हैं।" },
  { en: "Swati gives you independence like the free wind — adaptable, diplomatic, and self-made. You flourish when given space, and you negotiate beautifully. Root your freedom in a few firm commitments; the wind achieves most when it fills a chosen sail.",
    hi: "स्वाति आपको मुक्त पवन-सी स्वतंत्रता देती है — लचीले, कूटनीति में कुशल और स्वयं-निर्मित। खुला आकाश मिलते ही आप खिल उठते हैं और संवाद में संतुलन साध लेते हैं। अपनी स्वतंत्रता को कुछ दृढ़ संकल्पों से जोड़िए; पवन तभी सर्वाधिक सिद्ध करती है जब चुनी हुई पाल में भरती है।" },
  { en: "Vishakha grants you focused ambition — once you fix a goal, obstacles become fuel, and your persistence is legendary among those who know you. Victory follows you in stages. Celebrate milestones and companions along the way; the summit is sweeter shared.",
    hi: "विशाखा आपको लक्ष्य-केंद्रित महत्वाकांक्षा देती है — लक्ष्य निश्चित होते ही बाधाएँ ईंधन बन जाती हैं, आपकी लगन आपके परिचितों में प्रसिद्ध है। विजय चरणों में आपके पीछे चलती है। मार्ग के पड़ावों और साथियों का उत्सव मनाइए; बाँटा हुआ शिखर अधिक मधुर होता है।" },
  { en: "Anuradha is the star of devotion and friendship across boundaries — you build bridges where others see walls, and your loyalty in difficult times is your crown. Success often comes through alliances. Honour your own needs too; devotion includes the self.",
    hi: "अनुराधा भक्ति और सीमाओं के पार मित्रता का नक्षत्र है — जहाँ अन्य दीवारें देखते हैं, आप सेतु बनाते हैं, और कठिन समय की आपकी निष्ठा ही आपका मुकुट है। सफलता प्रायः सहयोग से आती है। अपनी आवश्यकताओं का भी मान रखें; भक्ति में स्वयं भी सम्मिलित है।" },
  { en: "Jyeshtha gives you the elder's seat — protective authority, sharp strategy, and the courage to stand alone for what is right. People seek your shelter in storms. Wear seniority lightly and mentor generously; your legacy is the people you raise.",
    hi: "ज्येष्ठा आपको ज्येष्ठ का आसन देती है — रक्षक अधिकार, पैनी रणनीति और उचित के लिए अकेले खड़े होने का साहस। संकट में लोग आपकी छाया खोजते हैं। बड़प्पन को सहजता से धारण करें और खुले मन से मार्गदर्शन दें; आपकी विरासत वे लोग हैं जिन्हें आप ऊपर उठाते हैं।" },
  { en: "Mula reaches for the root of everything — you are a truth-digger, unafraid of deep questions and fresh starts. Superficial answers never satisfy you. This depth is rare wealth; pace your transformations gently so loved ones can travel with you.",
    hi: "मूल हर वस्तु की जड़ तक पहुँचता है — आप सत्य के खोजी हैं, गहरे प्रश्नों और नई शुरुआतों से निर्भय। सतही उत्तर आपको कभी संतुष्ट नहीं करते। यह गहराई दुर्लभ संपदा है; अपने परिवर्तनों की गति सौम्य रखें ताकि प्रियजन साथ चल सकें।" },
  { en: "Purva Ashadha gives you invincible optimism — you declare bold visions and carry others on the tide of your confidence. Water finds a way, and so do you. Verify details before the big leap; then your victories become unstoppable and lasting.",
    hi: "पूर्वाषाढ़ा आपको अजेय आशावाद देती है — आप साहसिक स्वप्न घोषित करते हैं और अपने आत्मविश्वास की लहर पर औरों को भी ले चलते हैं। जल मार्ग खोज ही लेता है, और आप भी। बड़ी छलाँग से पहले विवरण परख लें; फिर आपकी विजयें अजेय और स्थायी हो जाती हैं।" },
  { en: "Uttara Ashadha grants victory that endures — you win not by speed but by unshakeable integrity and patient effort. Leaders and institutions trust you naturally. Your word is your monument; keep choosing the long right road over the short clever one.",
    hi: "उत्तराषाढ़ा स्थायी विजय देती है — आप गति से नहीं, अडिग सत्यनिष्ठा और धैर्यपूर्ण परिश्रम से जीतते हैं। नेतृत्व और संस्थाएँ आप पर सहज विश्वास करती हैं। आपका वचन ही आपका स्मारक है; छोटे चतुर मार्ग की जगह लंबा सही मार्ग चुनते रहिए।" },
  { en: "Shravana is the star of sacred listening — you learn from everything and everyone, and your counsel carries the weight of true understanding. Knowledge flows to you and through you. Protect quiet time for study and reflection; it is your power source.",
    hi: "श्रवण पवित्र श्रवण का नक्षत्र है — आप हर व्यक्ति और अनुभव से सीखते हैं, आपके परामर्श में सच्ची समझ का भार होता है। ज्ञान आपकी ओर बहता है और आपसे होकर बँटता है। अध्ययन और चिंतन के लिए एकांत समय सुरक्षित रखें; वही आपकी ऊर्जा का स्रोत है।" },
  { en: "Dhanishtha gives you rhythm and prosperity — music, timing, teamwork, and wealth-building all respond to your touch. You perform best with an audience or a team. Stay generous as you rise; shared prosperity is the melody that never fades.",
    hi: "धनिष्ठा आपको लय और समृद्धि देती है — संगीत, समय की समझ, टीम-भावना और धन-संचय, सब आपके स्पर्श से सधते हैं। दर्शकों या दल के संग आप सर्वश्रेष्ठ करते हैं। ऊँचाई पर भी उदार रहिए; बाँटी हुई समृद्धि वह राग है जो कभी नहीं थमता।" },
  { en: "Shatabhisha, the hundred healers, gives you the gift of solving what others call incurable — in technology, medicine, or human hearts. You value truth and solitude. Let trusted people in; the healer heals deepest in genuine connection.",
    hi: "शतभिषा, सौ वैद्यों का नक्षत्र, आपको वह वरदान देता है कि जिसे लोग असाध्य कहें, आप उसका समाधान खोज लें — तकनीक में, चिकित्सा में या मानव हृदयों में। आप सत्य और एकांत के प्रेमी हैं। विश्वस्त जनों को निकट आने दें; सच्चे जुड़ाव में ही चिकित्सक की गहनतम चिकित्सा होती है।" },
  { en: "Purva Bhadrapada gives you visionary fire — you sense higher purpose behind events and can inspire radical positive change. Your intensity is transformative. Ground your fire in daily sadhana; a steady lamp illumines more than a flare.",
    hi: "पूर्वाभाद्रपद आपको दूरदर्शी अग्नि देता है — घटनाओं के पीछे का उच्च प्रयोजन आप भाँप लेते हैं और गहरे शुभ परिवर्तन की प्रेरणा बन सकते हैं। आपकी तीव्रता रूपांतरकारी है। इस अग्नि को नित्य साधना में स्थिर करें; टिमटिमाती लौ से अधिक प्रकाश स्थिर दीपक देता है।" },
  { en: "Uttara Bhadrapada grants oceanic depth and calm — your patience outlasts every storm, and people find peace simply sitting near you. Wisdom matures early in you. Share it gently and often; your stillness is a gift this restless world needs.",
    hi: "उत्तराभाद्रपद सागर-सी गहराई और शांति देता है — आपका धैर्य हर तूफ़ान से लंबा है, लोग आपके निकट बैठकर ही शांति पा लेते हैं। ज्ञान आपमें शीघ्र परिपक्व होता है। उसे सहजता से बाँटते रहिए; आपकी स्थिरता इस अशांत संसार के लिए वरदान है।" },
  { en: "Revati, the final nakshatra, makes you a guide of safe journeys — nurturing, prosperous, and instinctively protective of the vulnerable. Completion is your art: you finish, you fulfil, you deliver people home. Guard your soft heart with wise company.",
    hi: "रेवती, अंतिम नक्षत्र, आपको सुरक्षित यात्राओं का पथ-प्रदर्शक बनाता है — पालक, समृद्ध और निर्बल के सहज रक्षक। पूर्णता आपकी कला है: आप कार्य पूर्ण करते हैं, वचन निभाते हैं, लोगों को उनके गंतव्य तक पहुँचाते हैं। अपने कोमल हृदय की रक्षा सत्संग से कीजिए।" }
  ];

  global.SD_CONTENT = C;
})(typeof window !== 'undefined' ? window : global);

// ---- Lagna personality (12), appended ----
(function(g){var C=g.SD_CONTENT;
C.lagna=[
  { en: "With Mesha rising, you meet life head-on — courageous, direct, and first to act when others hesitate. Leadership sits naturally on you. Channel the fire into one mission at a time, and your victories arrive faster than your impatience.", hi: "मेष लग्न के साथ आप जीवन का सामना सीधे करते हैं — साहसी, स्पष्ट, और जहाँ अन्य ठिठकें वहाँ पहले कदम बढ़ाने वाले। नेतृत्व आप पर सहज सजता है। इस अग्नि को एक समय में एक लक्ष्य दें; विजयें आपकी अधीरता से भी तेज़ पहुँचेंगी।" },
  { en: "Vrishabha rising gives you steadiness the world can build upon — patient, loyal, artistic, with a gift for creating lasting comfort and wealth. You finish what flightier people abandon. Welcome change occasionally; even the finest garden needs new seeds.", hi: "वृषभ लग्न आपको वह स्थिरता देता है जिस पर संसार भवन खड़ा कर सके — धैर्यवान, निष्ठावान, कला-प्रेमी, स्थायी सुख और संपत्ति रचने में कुशल। जो कार्य चंचल लोग छोड़ दें, आप पूर्ण करते हैं। कभी-कभी परिवर्तन का स्वागत करें; श्रेष्ठ उद्यान को भी नए बीज चाहिए।" },
  { en: "Mithuna rising makes you quicksilver-bright — curious, articulate, endlessly adaptable. You connect people and ideas effortlessly and learn anything fast. Choose depth for your favourite few subjects; the world rewards the brilliant specialist even more than the brilliant generalist.", hi: "मिथुन लग्न आपको पारद-सी चपल बुद्धि देता है — जिज्ञासु, वाक्पटु, हर परिस्थिति में ढल जाने वाले। आप व्यक्तियों और विचारों को सहज जोड़ देते हैं। अपने प्रिय विषयों में गहराई चुनिए; संसार प्रतिभाशाली विशेषज्ञ को और भी अधिक फल देता है।" },
  { en: "Karka rising gives you the strongest heart in the zodiac — intuitive, protective, and deeply loyal to home and roots. People heal in your care. Let logic partner your feelings in big decisions, and your legendary memory will store mostly the sweet.", hi: "कर्क लग्न आपको राशिचक्र का सबसे सशक्त हृदय देता है — सहज-बोधी, रक्षक, घर और जड़ों के प्रति गहरे निष्ठावान। आपकी छाया में लोग स्वस्थ होते हैं। बड़े निर्णयों में भावना के साथ तर्क को भी बैठाइए; तब आपकी विख्यात स्मृति अधिकतर मधुर ही संजोएगी।" },
  { en: "Simha rising crowns you with natural dignity — generous, warm, born for the centre of meaningful stages. Your confidence lifts entire rooms. Share the spotlight freely and praise others often; a king remembered for generosity rules forever.", hi: "सिंह लग्न आपको स्वाभाविक गरिमा का मुकुट देता है — उदार, ऊष्मापूर्ण, सार्थक मंचों के केंद्र के लिए जन्मे। आपका आत्मविश्वास पूरे सभागार को ऊपर उठाता है। प्रकाश बाँटिए और प्रशंसा खुलकर कीजिए; उदारता के लिए स्मरण किया गया राजा सदा राज करता है।" },
  { en: "Kanya rising gives you the craftsman's eye — precise, helpful, quietly brilliant at making systems and people function better. Your service is your worship. Release perfectionism toward yourself; you already exceed the standards you fear missing.", hi: "कन्या लग्न आपको शिल्पी की दृष्टि देता है — सूक्ष्म, सेवाभावी, व्यवस्थाओं और व्यक्तियों को बेहतर बनाने में मौन प्रतिभाशाली। सेवा ही आपकी पूजा है। स्वयं के प्रति पूर्णतावाद छोड़िए; जिन मापदंडों से चूकने का भय है, आप उन्हें पहले ही पार कर चुके हैं।" },
  { en: "Tula rising makes you the zodiac's diplomat-artist — balanced, gracious, with an instinct for fairness and beauty that draws people to you. Partnerships prosper around you. Practise deciding a little faster; your judgment is better than your doubt believes.", hi: "तुला लग्न आपको राशिचक्र का कूटनीतिज्ञ-कलाकार बनाता है — संतुलित, शालीन, न्याय और सौंदर्य की सहज समझ से लोग आपकी ओर खिंचते हैं। साझेदारियाँ आपके संग फलती हैं। निर्णय थोड़ा शीघ्र लेने का अभ्यास करें; आपका विवेक आपकी शंका से कहीं श्रेष्ठ है।" },
  { en: "Vrishchika rising gives you depth and regenerative power — you perceive hidden truths, survive what would break others, and return stronger every time. Your focus is a laser. Choose worthy targets and trusted confidants; then nothing in this world outlasts you.", hi: "वृश्चिक लग्न आपको गहराई और पुनर्जीवन की शक्ति देता है — आप छिपे सत्य देख लेते हैं, वह सह जाते हैं जो औरों को तोड़ दे, और हर बार प्रबल होकर लौटते हैं। आपकी एकाग्रता किरण-सी है। योग्य लक्ष्य और विश्वस्त साथी चुनिए; फिर इस संसार में कुछ भी आपसे अधिक टिक नहीं सकता।" },
  { en: "Dhanu rising fills you with the archer's optimism — philosophical, adventurous, honest to a fault, always aiming beyond the visible horizon. Fortune genuinely favours you. Aim, then also walk the full distance; arrows land where feet follow.", hi: "धनु लग्न आपको धनुर्धर का आशावाद देता है — दार्शनिक, साहसिक, स्पष्टवादी, सदा दृश्य क्षितिज से आगे लक्ष्य साधने वाले। भाग्य वास्तव में आपके पक्ष में रहता है। लक्ष्य साधिए, फिर पूरी दूरी चलिए भी; बाण वहीं पहुँचते हैं जहाँ चरण साथ चलते हैं।" },
  { en: "Makara rising gives you the mountain-climber's soul — disciplined, responsible, unhurried, and utterly unstoppable over time. You build things that outlive trends. Schedule joy as seriously as duty; the summit is for living, not only reaching.", hi: "मकर लग्न आपको पर्वतारोही की आत्मा देता है — अनुशासित, उत्तरदायी, अविचल, और समय के साथ पूर्णतः अजेय। आप वह रचते हैं जो प्रचलनों से आगे जीता है। आनंद को भी कर्तव्य जितनी गंभीरता से समय दीजिए; शिखर पहुँचने के लिए नहीं, जीने के लिए है।" },
  { en: "Kumbha rising makes you the visionary friend of humanity — original, principled, comfortable being years ahead of your time. Communities form around your ideas. Keep translating vision into small practical steps; the future arrives through them.", hi: "कुंभ लग्न आपको मानवता का दूरदर्शी मित्र बनाता है — मौलिक, सिद्धांतनिष्ठ, अपने समय से वर्षों आगे रहने में सहज। आपके विचारों के चारों ओर समुदाय बनते हैं। स्वप्न को छोटे व्यावहारिक चरणों में उतारते रहिए; भविष्य उन्हीं से होकर आता है।" },
  { en: "Meena rising gives you the ocean's compassion — imaginative, intuitive, spiritually gifted, dissolving boundaries between yourself and those who suffer. Art and devotion flow through you. Anchor your days with one firm routine; the ocean is mightiest with a shore.", hi: "मीन लग्न आपको सागर-सी करुणा देता है — कल्पनाशील, अंतर्दृष्टि-संपन्न, आध्यात्मिक प्रतिभा से युक्त, दुखियों और स्वयं के बीच की सीमा मिटा देने वाले। कला और भक्ति आपसे होकर बहती है। दिन को एक दृढ़ नियम से बाँधिए; तट के संग ही सागर सर्वाधिक शक्तिशाली होता है।" },
];
C.dashaLord={
  ketu: { en: "Ketu Mahadasha (7 years) turns life inward — a period of spiritual ripening, sudden insights, and release of what no longer serves. Material events may feel unpredictable, but inner growth is guaranteed. Best used for sadhana, research, and letting go gracefully.", hi: "केतु महादशा (7 वर्ष) जीवन को अंतर्मुखी करती है — आध्यात्मिक परिपक्वता, आकस्मिक बोध और अनावश्यक के त्याग का काल। बाह्य घटनाएँ अनिश्चित लग सकती हैं, पर आंतरिक विकास निश्चित है। साधना, शोध और सहज त्याग के लिए यह श्रेष्ठ समय है।" },
  venus: { en: "Shukra Mahadasha (20 years) is the season of love, comfort and creativity — relationships deepen, arts flourish, and material pleasures arrive generously. Wealth grows through people skills and aesthetics. Enjoy nobly and stay disciplined; sweetness lasts when savoured slowly.", hi: "शुक्र महादशा (20 वर्ष) प्रेम, सुख और सृजन का ऋतुकाल है — संबंध गहराते हैं, कलाएँ खिलती हैं, भौतिक सुख उदारता से आते हैं। धन जन-कौशल और सौंदर्य-दृष्टि से बढ़ता है। कुलीनता से आनंद लीजिए और संयम रखिए; धीरे चखी गई मिठास ही देर तक टिकती है।" },
  sun: { en: "Surya Mahadasha (6 years) brings authority and visibility — recognition from superiors, government matters, and leadership roles activate. Your name shines brighter. Health of father and your own vitality deserve care; humility keeps the crown steady.", hi: "सूर्य महादशा (6 वर्ष) अधिकार और प्रतिष्ठा लाती है — वरिष्ठों से मान, शासकीय कार्य और नेतृत्व की भूमिकाएँ सक्रिय होती हैं। आपका नाम अधिक चमकता है। पिता के स्वास्थ्य और अपनी ऊर्जा का ध्यान रखें; विनम्रता ही मुकुट को स्थिर रखती है।" },
  moon: { en: "Chandra Mahadasha (10 years) softens and enriches life — mind becomes receptive, public support grows, home and mother themes become central, and travel across waters is indicated. Emotional self-care is your superpower now; a calm moon commands the tides.", hi: "चंद्र महादशा (10 वर्ष) जीवन को कोमल और समृद्ध करती है — मन ग्रहणशील होता है, जन-समर्थन बढ़ता है, घर और माता के विषय केंद्र में आते हैं, जल-पार यात्रा के योग बनते हैं। मन की देखभाल अभी आपकी महाशक्ति है; शांत चंद्रमा ही ज्वार पर शासन करता है।" },
  mars: { en: "Mangal Mahadasha (7 years) ignites courage and action — property matters, competitions, technical skills, and physical energy all surge. Bold moves succeed now. Channel heat through exercise and clear goals; a directed flame forges, a wild one burns.", hi: "मंगल महादशा (7 वर्ष) साहस और कर्म प्रज्वलित करती है — भूमि-संपत्ति, प्रतियोगिताएँ, तकनीकी कौशल और शारीरिक ऊर्जा, सब बढ़ते हैं। साहसिक कदम अभी सफल होते हैं। इस ताप को व्यायाम और स्पष्ट लक्ष्य दें; दिशा-युक्त अग्नि गढ़ती है, दिशाहीन जलाती है।" },
  rahu: { en: "Rahu Mahadasha (18 years) is the great amplifier — foreign connections, technology, unconventional paths and sudden rises mark this era. Ambitions realized here can be enormous. Verify shortcuts and keep dharma as your compass; Rahu rewards the bold-with-ethics richly.", hi: "राहु महादशा (18 वर्ष) महान वर्धक है — विदेश-संबंध, तकनीक, अपरंपरागत मार्ग और आकस्मिक उत्थान इस युग की पहचान हैं। यहाँ पूर्ण हुई महत्वाकांक्षाएँ विशाल हो सकती हैं। शॉर्टकट परख लें और धर्म को दिशासूचक रखें; नीति-युक्त साहसी को राहु भरपूर देता है।" },
  jupiter: { en: "Guru Mahadasha (16 years) is the golden season of wisdom and grace — education, children, spiritual growth, respected mentors and honourable prosperity all expand. Blessings often arrive through teachers and your own teaching. Give knowledge freely; Guru returns it multiplied.", hi: "गुरु महादशा (16 वर्ष) ज्ञान और कृपा का स्वर्णकाल है — विद्या, संतान, आध्यात्मिक उन्नति, सम्मानित मार्गदर्शक और मर्यादित समृद्धि, सबका विस्तार होता है। आशीर्वाद प्रायः गुरुजनों से और आपके अपने शिक्षण से आते हैं। ज्ञान मुक्त हस्त से दीजिए; गुरु उसे कई गुना लौटाते हैं।" },
  saturn: { en: "Shani Mahadasha (19 years) builds your permanent legacy — through patience, discipline and honest labour, structures rise that nothing can shake. Rewards may come slowly but they come surely and stay. Serve the humble, respect time, and Shani becomes your strongest ally.", hi: "शनि महादशा (19 वर्ष) आपकी स्थायी विरासत गढ़ती है — धैर्य, अनुशासन और निष्कपट परिश्रम से ऐसे आधार बनते हैं जिन्हें कोई हिला न सके। फल धीमे आएँ पर निश्चित आते हैं और टिकते हैं। दीन की सेवा करें, समय का मान रखें; तब शनि आपके प्रबलतम मित्र बन जाते हैं।" },
  mercury: { en: "Budha Mahadasha (17 years) sharpens intellect and commerce — communication, business, writing, analytics and networks thrive. Multiple income streams become natural. Keep learning new skills each year; Budha crowns the perpetual student with green prosperity.", hi: "बुध महादशा (17 वर्ष) बुद्धि और व्यापार को तीक्ष्ण करती है — संवाद, व्यवसाय, लेखन, विश्लेषण और संपर्क-जाल फलते-फूलते हैं। आय के अनेक स्रोत सहज बनते हैं। प्रतिवर्ष नया कौशल सीखते रहिए; बुध नित्य-विद्यार्थी को हरित समृद्धि का मुकुट पहनाते हैं।" },
};
C.remedy={
  sun: { name: "Surya", mantra: "ॐ घृणिः सूर्याय नमः", en: "Offer water to the rising Sun; respect father and elders; donate wheat or jaggery on Sundays.", hi: "उगते सूर्य को जल अर्पित करें; पिता व गुरुजनों का सम्मान करें; रविवार को गेहूँ या गुड़ का दान करें।" },
  moon: { name: "Chandra", mantra: "ॐ सों सोमाय नमः", en: "Keep Monday calm and clean; honour mother; offer milk or rice to the needy on Mondays.", hi: "सोमवार शांत व सात्विक रखें; माता का आदर करें; सोमवार को दूध या चावल का दान करें।" },
  mars: { name: "Mangal", mantra: "ॐ अं अंगारकाय नमः", en: "Recite Hanuman Chalisa on Tuesdays; practise physical discipline; donate masoor dal or red cloth.", hi: "मंगलवार को हनुमान चालीसा पढ़ें; शारीरिक अनुशासन रखें; मसूर दाल या लाल वस्त्र का दान करें।" },
  mercury: { name: "Budha", mantra: "ॐ बुं बुधाय नमः", en: "Feed green fodder to cows on Wednesdays; keep speech truthful and sweet; donate green moong.", hi: "बुधवार को गौ को हरा चारा खिलाएँ; वाणी सत्य और मधुर रखें; हरे मूँग का दान करें।" },
  jupiter: { name: "Guru", mantra: "ॐ बृं बृहस्पतये नमः", en: "Serve teachers and share knowledge on Thursdays; donate turmeric, chana dal or books.", hi: "गुरुवार को गुरुजनों की सेवा और ज्ञान-दान करें; हल्दी, चने की दाल या पुस्तकों का दान करें।" },
  venus: { name: "Shukra", mantra: "ॐ शुं शुक्राय नमः", en: "Keep Fridays artistic and generous; respect women; donate white sweets, rice or curd.", hi: "शुक्रवार को कला और उदारता से जोड़ें; स्त्रियों का सम्मान करें; श्वेत मिष्ठान, चावल या दही का दान करें।" },
  saturn: { name: "Shani", mantra: "ॐ शं शनैश्चराय नमः", en: "Serve the elderly, workers and the disabled on Saturdays; light a sesame-oil lamp; donate black til or iron.", hi: "शनिवार को वृद्धों, श्रमिकों और असहायों की सेवा करें; तिल के तेल का दीप जलाएँ; काले तिल या लोहे का दान करें।" },
  rahu: { name: "Rahu", mantra: "ॐ रां राहवे नमः", en: "Maintain ethical clarity in ambitions; feed birds; donate blankets to the poor on Saturdays.", hi: "महत्वाकांक्षाओं में नैतिक स्पष्टता रखें; पक्षियों को दाना डालें; शनिवार को निर्धनों को कंबल दान करें।" },
  ketu: { name: "Ketu", mantra: "ॐ कें केतवे नमः", en: "Practise daily meditation or japa; care for stray dogs; donate multicoloured blankets or til.", hi: "नित्य ध्यान या जप करें; निराश्रित श्वानों की देखभाल करें; चितकबरे कंबल या तिल का दान करें।" },
};
C.yoga={
  gajaKesari: { en: "Gaja Kesari Yoga — Jupiter blesses your Moon from a kendra: wisdom, reputation and lasting respect grow throughout life; elders and institutions favour you.", hi: "गजकेसरी योग — गुरु आपके चंद्रमा को केंद्र से आशीर्वाद देते हैं: बुद्धि, कीर्ति और स्थायी सम्मान जीवन भर बढ़ते हैं; गुरुजन और संस्थाएँ आपके पक्ष में रहती हैं।" },
  budhaditya: { en: "Budhaditya Yoga — Sun and Mercury unite: sharp intellect, administrative talent and success in studies, writing and analysis.", hi: "बुधादित्य योग — सूर्य और बुध का मिलन: तीक्ष्ण बुद्धि, प्रशासनिक प्रतिभा और अध्ययन, लेखन व विश्लेषण में सफलता।" },
  chandraMangal: { en: "Chandra-Mangal Yoga — Moon with Mars: earning power, enterprise and the courage to act on feelings; wealth through self-effort.", hi: "चंद्र-मंगल योग — चंद्र संग मंगल: अर्जन-शक्ति, उद्यम और भावना को कर्म में बदलने का साहस; स्व-पुरुषार्थ से धन।" },
  ruchaka: { en: "Ruchaka Yoga (Mahapurusha) — Mars strong in a kendra: courage, command and physical excellence mark your path; a natural warrior-leader.", hi: "रुचक योग (पंचमहापुरुष) — केंद्र में बली मंगल: साहस, नेतृत्व-आदेश और शारीरिक श्रेष्ठता आपके पथ की पहचान; स्वाभाविक योद्धा-नायक।" },
  bhadra: { en: "Bhadra Yoga (Mahapurusha) — Mercury strong in a kendra: brilliant intellect, eloquence and enduring youthful charm; success in commerce and communication.", hi: "भद्र योग (पंचमहापुरुष) — केंद्र में बली बुध: प्रखर बुद्धि, वाक्पटुता और चिर-यौवन आकर्षण; वाणिज्य और संवाद में सफलता।" },
  hamsa: { en: "Hamsa Yoga (Mahapurusha) — Jupiter strong in a kendra: righteousness, learning and honour; you are respected like a swan among birds.", hi: "हंस योग (पंचमहापुरुष) — केंद्र में बली गुरु: धर्मनिष्ठा, विद्या और मान; पक्षियों में हंस-सा आदर आपको प्राप्त है।" },
  malavya: { en: "Malavya Yoga (Mahapurusha) — Venus strong in a kendra: refinement, artistic gifts, vehicles, comforts and a gracious married life are indicated.", hi: "मालव्य योग (पंचमहापुरुष) — केंद्र में बली शुक्र: परिष्कार, कला-प्रतिभा, वाहन-सुख और सौम्य दांपत्य जीवन के संकेत।" },
  shasha: { en: "Shasha Yoga (Mahapurusha) — Saturn strong in a kendra: authority over people and land, discipline and durable power, especially in later life.", hi: "शश योग (पंचमहापुरुष) — केंद्र में बली शनि: जन और भूमि पर अधिकार, अनुशासन और स्थायी सत्ता, विशेषतः उत्तरार्ध जीवन में।" },
  harsha: { en: "Harsha Yoga (Vipreet) — hardships transform into happiness; enemies retreat and health strengthens after challenges.", hi: "हर्ष योग (विपरीत राजयोग) — कठिनाइयाँ सुख में बदलती हैं; चुनौतियों के बाद शत्रु पीछे हटते हैं और स्वास्थ्य सुदृढ़ होता है।" },
  sarala: { en: "Sarala Yoga (Vipreet) — fearlessness and victory through crises; what threatens others becomes your ladder.", hi: "सरल योग (विपरीत राजयोग) — संकटों के बीच निर्भयता और विजय; जो औरों के लिए भय है, वही आपकी सीढ़ी बनता है।" },
  vimala: { en: "Vimala Yoga (Vipreet) — economy of expenses, independence and a spotless reputation grow with time.", hi: "विमल योग (विपरीत राजयोग) — व्यय-संयम, स्वावलंबन और निष्कलंक कीर्ति समय के साथ बढ़ती है।" },
  raja: { en: "Raja Yoga — lords of kendra and trikona unite: rise in status, favour from authority and success that uplifts your whole family line.", hi: "राजयोग — केंद्र और त्रिकोण के स्वामियों का मिलन: पद-प्रतिष्ठा में उत्थान, सत्ता की कृपा और ऐसी सफलता जो पूरे कुल को ऊपर उठाए।" },
  dhana: { en: "Dhana Yoga — wealth lords combine: strong earning combinations; prosperity grows through multiple streams.", hi: "धन योग — धनेश-लाभेश का संयोग: प्रबल अर्जन-योग; अनेक स्रोतों से समृद्धि बढ़ती है।" },
  kemadruma: { en: "Kemadruma is indicated by the Moon standing alone — early struggles are possible, yet classical texts list many cancellations, and self-made success is this yoga's famous other face. Steady sadhana and good company dissolve its shadow.", hi: "केमद्रुम योग — चंद्रमा का एकाकी होना: प्रारंभिक संघर्ष संभव हैं, किंतु शास्त्रों में इसके अनेक भंग-नियम हैं, और स्वयं-निर्मित सफलता इसी योग का प्रसिद्ध दूसरा मुख है। नित्य साधना और सत्संग इसकी छाया मिटा देते हैं।" },
};
C.dosha={
  manglikYes:{en:"Mangal Dosha is present in the Lagna chart (Mars influences the marriage houses). Classical texts prescribe many cancellations and it commonly softens greatly after age 28; matching with a compatible chart and Mangal sadhana (Hanuman upasana on Tuesdays) are the time-honoured paths.",hi:"लग्न कुंडली में मंगल दोष है (मंगल विवाह-भावों को प्रभावित करता है)। शास्त्रों में इसके अनेक परिहार हैं और 28 वर्ष की आयु के बाद यह प्रायः बहुत शांत हो जाता है; अनुकूल कुंडली से मिलान तथा मंगलवार को हनुमान-उपासना इसके शास्त्रसम्मत मार्ग हैं।"},
  manglikNo:{en:"No Mangal Dosha in the Lagna chart — Mars sits peacefully for marriage matters.",hi:"लग्न कुंडली में मंगल दोष नहीं है — विवाह के विषय में मंगल शांत स्थित हैं।"},
  kaalSarpYes:{en:"A Kaal Sarpa configuration is present ({type}). Tradition reads it as concentrated karmic focus: extraordinary rises follow disciplined effort. Rahu-Ketu shanti, Nag Panchami observance and steady japa are the classical supports.",hi:"कुंडली में कालसर्प स्थिति ({type}) विद्यमान है। परंपरा इसे केंद्रित कर्म-शक्ति मानती है: अनुशासित पुरुषार्थ के बाद असाधारण उत्थान आते हैं। राहु-केतु शांति, नागपंचमी व्रत और नियमित जप इसके शास्त्रीय आधार हैं।"},
  kaalSarpNo:{en:"No Kaal Sarpa configuration — the planets stand freely on both sides of the nodal axis.",hi:"कालसर्प स्थिति नहीं है — ग्रह राहु-केतु अक्ष के दोनों ओर मुक्त स्थित हैं।"},
  sadeSatiActive:{en:"Saturn is currently transiting your Sade Sati zone ({phase}). This is Shani the teacher, not the punisher: responsibilities deepen, foundations get tested and rebuilt stronger. Discipline, humility and Saturday seva convert this period into lifelong assets.",hi:"शनि इस समय आपके साढ़े साती क्षेत्र ({phase}) में गोचर कर रहे हैं। यह दंड नहीं, शिक्षक-शनि हैं: उत्तरदायित्व गहराते हैं, नींव परखी जाकर और सुदृढ़ होती है। अनुशासन, विनम्रता और शनिवार की सेवा इस काल को आजीवन पूँजी में बदल देती है।"},
  sadeSatiNo:{en:"Sade Sati is not active at present. The next period is shown in the table with exact dates — awareness in advance is itself half the remedy.",hi:"वर्तमान में साढ़े साती सक्रिय नहीं है। आगामी अवधि तालिका में तिथियों सहित दी गई है — पूर्व-जानकारी स्वयं आधा उपाय है।"}
};
C.labels={
  reportTitle:{en:"Janma Kundli Report",hi:"जन्म कुंडली रिपोर्ट"},
  by:{en:"Shubh Din · shubhdin.app",hi:"शुभ दिन · shubhdin.app"},
  free:{en:"Complete Kundli — Free, Accurate, Verifiable",hi:"संपूर्ण कुंडली — निःशुल्क, शुद्ध, सत्यापन-योग्य"},
  birthPanchang:{en:"Birth Panchang",hi:"जन्म पंचांग"},
  charts:{en:"Kundli Charts",hi:"कुंडली चक्र"},
  positions:{en:"Planetary Positions",hi:"ग्रह स्थिति"},
  yourNak:{en:"Your Birth Nakshatra",hi:"आपका जन्म नक्षत्र"},
  yourLagna:{en:"Your Lagna (Ascendant)",hi:"आपका लग्न"},
  yogasFound:{en:"Auspicious Yogas in Your Kundli",hi:"आपकी कुंडली के शुभ योग"},
  dignity:{en:"Planetary Dignities",hi:"ग्रह-गरिमा"},
  ashtak:{en:"Sarvashtakavarga (House Strength)",hi:"सर्वाष्टकवर्ग (भाव-बल)"},
  doshas:{en:"Dosha Analysis — with honest context",hi:"दोष विश्लेषण — संतुलित दृष्टि सहित"},
  dashaTimeline:{en:"Vimshottari Dasha Timeline",hi:"विंशोत्तरी दशा क्रम"},
  currentDasha:{en:"Your Current Period",hi:"आपकी वर्तमान दशा"},
  sadeSati:{en:"Shani Sade Sati Periods",hi:"शनि साढ़े साती अवधियाँ"},
  remedies:{en:"Remedies as Sadhana",hi:"उपाय — साधना रूप में"},
  remedyNote:{en:"Shubh Din prescribes no gemstones and sells nothing. These classical remedies cost only devotion: mantra, seva and daan.",hi:"शुभ दिन कोई रत्न नहीं बताता, कुछ नहीं बेचता। ये शास्त्रीय उपाय केवल श्रद्धा माँगते हैं: मंत्र, सेवा और दान।"},
  verify:{en:"Every calculation in this report follows Drik Ganita (Lahiri ayanamsa) and can be verified against any standard panchang. Guidance is offered in the spirit of tradition, for reflection — your karma and effort remain supreme.",hi:"इस रिपोर्ट की प्रत्येक गणना दृक् गणित (लाहिरी अयनांश) से है और किसी भी मानक पंचांग से सत्यापित की जा सकती है। मार्गदर्शन परंपरा की भावना से, चिंतन हेतु है — आपका कर्म और पुरुषार्थ ही सर्वोपरि है।"},
  house:{en:"House",hi:"भाव"}, rashiW:{en:"Rashi",hi:"राशि"}, from:{en:"From",hi:"से"}, to:{en:"To",hi:"तक"}
};
})(typeof window!=='undefined'?window:global);

(function(g){var C=g.SD_CONTENT; C.antar=C.antar||{};
C.antar["ketu-ketu"]={en:"Ketu–Ketu period intensifies introspection — worldly noise fades and spiritual questions grow louder. Excellent for meditation, research and pilgrimage. Keep decisions minimal and routines steady; clarity arrives near the period's end.",hi:"केतु–केतु काल अंतर्मुखता को गहराता है — सांसारिक कोलाहल मंद पड़ता है और आध्यात्मिक प्रश्न मुखर होते हैं। ध्यान, शोध और तीर्थ हेतु उत्तम। निर्णय न्यूनतम और दिनचर्या स्थिर रखें; स्पष्टता अवधि के अंत के निकट आती है।"};
C.antar["ketu-venus"]={en:"Ketu–Shukra softens the austerity — comforts return, artistic inspiration flows, and relationships ask for gentle attention. Detached enjoyment is the secret: love without clinging, spend without craving.",hi:"केतु–शुक्र संयम को कोमल करता है — सुख लौटते हैं, कला-प्रेरणा बहती है, संबंध सौम्य ध्यान माँगते हैं। अनासक्त आनंद ही रहस्य है: बिना बंधन प्रेम, बिना तृष्णा व्यय।"};
C.antar["ketu-sun"]={en:"Ketu–Surya tests recognition — authority may feel distant, yet inner authority strengthens beautifully. Health of father and your vitality deserve care. Work sincerely without chasing applause; respect follows unasked.",hi:"केतु–सूर्य मान-सम्मान की परीक्षा लेता है — बाह्य सत्ता दूर लगे, पर आंतरिक तेज सुंदर रूप से बढ़ता है। पिता के स्वास्थ्य और अपनी ऊर्जा का ध्यान रखें। प्रशंसा का पीछा किए बिना निष्ठा से कार्य करें; आदर स्वयं चला आता है।"};
C.antar["ketu-moon"]={en:"Ketu–Chandra makes the mind subtle and sensitive — dreams vivid, intuition sharp, moods tidal. Protect sleep, stay near water and mother-figures, practise japa. Emotional insights gained now guide you for years.",hi:"केतु–चंद्र मन को सूक्ष्म और संवेदनशील करता है — स्वप्न सजीव, अंतर्ज्ञान तीव्र, भाव ज्वार-से। निद्रा की रक्षा करें, जल और मातृ-स्वरूपों के निकट रहें, जप करें। अभी मिले भाव-बोध वर्षों मार्ग दिखाते हैं।"};
C.antar["ketu-mars"]={en:"Ketu–Mangal concentrates courage into precision — technical mastery, tantric focus and decisive action succeed. Guard against haste and minor injuries; measured boldness wins everything this period offers.",hi:"केतु–मंगल साहस को सूक्ष्म एकाग्रता देता है — तकनीकी दक्षता, गहन साधना और निर्णायक कर्म सफल होते हैं। जल्दबाज़ी और छोटी चोटों से सावधान रहें; संयत पराक्रम इस काल का सब कुछ जीत लेता है।"};
C.antar["ketu-rahu"]={en:"Ketu–Rahu is the axis meeting itself — sudden shifts in direction are possible, old identities dissolve, new unconventional doors open. Change less, observe more; the dust settles into unexpected opportunity.",hi:"केतु–राहु अक्ष का स्वयं से मिलन है — दिशा में आकस्मिक मोड़ संभव, पुरानी पहचानें विलीन होती हैं, नए अपरंपरागत द्वार खुलते हैं। बदलें कम, देखें अधिक; धूल बैठते ही अप्रत्याशित अवसर दिखता है।"};
C.antar["ketu-jupiter"]={en:"Ketu–Guru is grace within detachment — wise mentors appear, philosophical study deepens, and blessings arrive quietly. An excellent window for higher learning, mantra-diksha and charitable resolve.",hi:"केतु–गुरु वैराग्य में कृपा है — ज्ञानी मार्गदर्शक मिलते हैं, दर्शन-अध्ययन गहराता है, आशीर्वाद मौन रूप से आते हैं। उच्च विद्या, मंत्र-दीक्षा और दान-संकल्प हेतु उत्तम अवधि।"};
C.antar["ketu-saturn"]={en:"Ketu–Shani asks for patient endurance — duties feel heavy but each one discharged now clears old karma permanently. Serve elders and workers, keep the body warm and active; late in the period, burdens visibly lighten.",hi:"केतु–शनि धैर्यपूर्ण सहनशीलता माँगता है — कर्तव्य भारी लगें पर अभी निभाया हर कर्तव्य पुराना कर्म सदा के लिए काटता है। वृद्धों-श्रमिकों की सेवा करें, शरीर सक्रिय रखें; अवधि के उत्तरार्ध में बोझ स्पष्ट हल्के होते हैं।"};
C.antar["ketu-mercury"]={en:"Ketu–Budha sharpens subtle intellect — research, coding, astrology and diagnostic skills flourish. Communication may feel misread at times; write things down, double-confirm agreements, and let your work speak.",hi:"केतु–बुध सूक्ष्म बुद्धि को तीक्ष्ण करता है — शोध, तकनीक, ज्योतिष और निदान-कौशल खिलते हैं। संवाद कभी-कभी गलत समझा जा सकता है; लिखकर रखें, समझौते दोबारा पक्के करें, और कार्य को बोलने दें।"};
C.antar["venus-venus"]={en:"Shukra–Shukra is the honeymoon of the great Venus era — love, luxury, art and income flow at their sweetest. Invest in beauty that lasts: relationships, skills, assets. Moderation keeps the nectar from turning heavy.",hi:"शुक्र–शुक्र महाशुक्र युग का मधुमास है — प्रेम, वैभव, कला और आय अपने मधुरतम रूप में बहते हैं। स्थायी सौंदर्य में निवेश करें: संबंध, कौशल, संपत्ति। संयम ही इस अमृत को भारी होने से बचाता है।"};
C.antar["venus-sun"]={en:"Shukra–Surya brings glamour before authority — recognition in creative or public work, support from seniors, possible honours. Balance charm with substance; deliver excellence behind the shine.",hi:"शुक्र–सूर्य सत्ता के समक्ष आभा लाता है — रचनात्मक या सार्वजनिक कार्य में पहचान, वरिष्ठों का सहयोग, सम्मान संभव। आकर्षण के साथ सार भी रखें; चमक के पीछे श्रेष्ठ कार्य दें।"};
C.antar["venus-moon"]={en:"Shukra–Chandra is emotional springtime — family joy, romance, vehicles and home comforts expand. Public dealings favour you. Keep finances gently disciplined amid the festivities.",hi:"शुक्र–चंद्र भावनाओं का वसंत है — पारिवारिक आनंद, प्रेम, वाहन और गृह-सुख का विस्तार। जन-व्यवहार आपके पक्ष में। उत्सवों के बीच धन में सौम्य अनुशासन रखें।"};
C.antar["venus-mars"]={en:"Shukra–Mangal ignites passion and earnings — bold ventures, property deals and courtship all heat up. Channel desire through commitment and exercise; impulsive spending is the only trap.",hi:"शुक्र–मंगल जोश और अर्जन प्रज्वलित करता है — साहसिक उद्यम, संपत्ति-सौदे और प्रणय, सब गरमाते हैं। इच्छा को प्रतिबद्धता और व्यायाम की दिशा दें; आवेगी खर्च ही एकमात्र जाल है।"};
C.antar["venus-rahu"]={en:"Shukra–Rahu amplifies desires and foreign flavours — sudden gains, imported comforts, unconventional relationships or media exposure possible. Verify glitter for gold; contracts need fine print reading.",hi:"शुक्र–राहु इच्छाओं और विदेशी रंगों को बढ़ाता है — आकस्मिक लाभ, आयातित सुख, अपरंपरागत संबंध या प्रचार-प्रसिद्धि संभव। चमक में सोना परख लें; अनुबंधों की बारीक शर्तें अवश्य पढ़ें।"};
C.antar["venus-jupiter"]={en:"Shukra–Guru unites the two benefics — marriage, children, wealth and blessings from teachers are classically indicated. Generosity multiplies fortune now; celebrate and share widely.",hi:"शुक्र–गुरु दोनों शुभ ग्रहों का मिलन है — विवाह, संतान, धन और गुरुजनों के आशीर्वाद के शास्त्रीय संकेत। उदारता अभी भाग्य को कई गुना करती है; उत्सव मनाएँ और बाँटें।"};
C.antar["venus-saturn"]={en:"Shukra–Shani matures pleasures into commitments — long-term relationships, property structures and steady income build. Romance becomes responsibility, sweetly. Honour promises and the period rewards richly.",hi:"शुक्र–शनि सुखों को परिपक्व प्रतिबद्धता देता है — दीर्घ संबंध, संपत्ति-आधार और स्थिर आय बनती है। प्रणय मधुरता से उत्तरदायित्व बनता है। वचन निभाइए, यह काल भरपूर फल देता है।"};
C.antar["venus-mercury"]={en:"Shukra–Budha blends art with commerce — writing, design, trade and negotiations sparkle. Multiple income streams open. Keep accounts clean and words sweet; both are money now.",hi:"शुक्र–बुध कला और वाणिज्य का संगम है — लेखन, डिज़ाइन, व्यापार और वार्ताएँ चमकती हैं। आय के अनेक स्रोत खुलते हैं। हिसाब स्वच्छ और वाणी मधुर रखें; दोनों अभी धन हैं।"};
C.antar["venus-ketu"]={en:"Shukra–Ketu refines taste toward the eternal — material pleasures may briefly lose flavour while devotion and art gain depth. Simplify possessions, deepen one relationship, and beauty returns purified.",hi:"शुक्र–केतु रुचि को शाश्वत की ओर परिष्कृत करता है — भौतिक सुख क्षण भर फीके लगें, पर भक्ति और कला गहराती हैं। संग्रह सरल करें, एक संबंध गहरा करें; सौंदर्य शुद्ध होकर लौटता है।"};
C.antar["sun-sun"]={en:"Surya–Surya doubles the royal fire — leadership calls, government matters progress, and your name carries new weight. Health and ego both run hot; humility and hydration keep the crown comfortable.",hi:"सूर्य–सूर्य राजसी तेज दोगुना करता है — नेतृत्व पुकारता है, शासकीय कार्य बढ़ते हैं, नाम में नया भार आता है। स्वास्थ्य और अहं दोनों तप्त रहते हैं; विनम्रता और संयम मुकुट को सुखद रखते हैं।"};
C.antar["sun-moon"]={en:"Surya–Chandra balances authority with empathy — public support meets official favour; excellent for roles bridging leadership and care. Parents' wellbeing deserves attention; your inner balance is the asset.",hi:"सूर्य–चंद्र सत्ता और संवेदना साधता है — जन-समर्थन और अधिकारिक कृपा साथ मिलते हैं; नेतृत्व-सेवा जोड़ने वाली भूमिकाओं हेतु उत्तम। माता-पिता का स्वास्थ्य ध्यान माँगता है; आपका आंतरिक संतुलन ही पूँजी है।"};
C.antar["sun-mars"]={en:"Surya–Mangal is command energy at full blaze — promotions, victories in competition and technical authority favoured. Watch temper and blood-pressure; a cool head atop this fire conquers all.",hi:"सूर्य–मंगल पूर्ण प्रज्वलित आदेश-ऊर्जा है — पदोन्नति, प्रतिस्पर्धा में विजय और तकनीकी अधिकार के योग। क्रोध और रक्तचाप पर दृष्टि रखें; इस अग्नि पर शांत मस्तिष्क सब जीत लेता है।"};
C.antar["sun-rahu"]={en:"Surya–Rahu brings eclipse-lessons around status — sudden visibility, foreign or political dealings, and tests of reputation. Stay transparently ethical; shadows pass, and you emerge more prominent.",hi:"सूर्य–राहु प्रतिष्ठा से जुड़े ग्रहण-पाठ लाता है — आकस्मिक प्रसिद्धि, विदेशी या राजनीतिक व्यवहार, और कीर्ति की परीक्षाएँ। पारदर्शी नैतिकता रखें; छायाएँ बीतती हैं और आप अधिक तेजस्वी निकलते हैं।"};
C.antar["sun-jupiter"]={en:"Surya–Guru is the king blessed by the guru — honours, education milestones, righteous authority and support from institutions. Children and mentors bring joy. Lead by dharma and doors keep opening.",hi:"सूर्य–गुरु गुरु-आशीर्वादित राजा है — सम्मान, शिक्षा-उपलब्धियाँ, धर्मसम्मत अधिकार और संस्थाओं का सहयोग। संतान और गुरुजन आनंद देते हैं। धर्म से नेतृत्व करें, द्वार खुलते रहेंगे।"};
C.antar["sun-saturn"]={en:"Surya–Shani pits light against time — friction with authority or delays possible, yet every duty honoured now builds unshakeable standing. Father-son themes seek healing. Patience is promotion in disguise.",hi:"सूर्य–शनि प्रकाश और काल की परीक्षा है — सत्ता से मतभेद या विलंब संभव, पर अभी निभाया हर कर्तव्य अटल प्रतिष्ठा गढ़ता है। पिता-संतान संबंध स्नेह माँगते हैं। धैर्य ही छिपी पदोन्नति है।"};
C.antar["sun-mercury"]={en:"Surya–Budha crowns intellect — administrative brilliance, exams, contracts and public speaking succeed. Ideal for launching studies or ventures needing both authority and cleverness.",hi:"सूर्य–बुध बुद्धि का राज्याभिषेक है — प्रशासनिक प्रखरता, परीक्षाएँ, अनुबंध और वक्तृत्व सफल होते हैं। जहाँ अधिकार और चातुर्य दोनों चाहिए, ऐसे अध्ययन-उद्यम आरंभ हेतु आदर्श।"};
C.antar["sun-ketu"]={en:"Surya–Ketu dims outer applause to light the inner lamp — a spiritual pause within an ambitious era. Delegate more, meditate more; identity refined now shines brighter in coming periods.",hi:"सूर्य–केतु बाहरी करतल-ध्वनि मंद कर भीतर का दीप जलाता है — महत्वाकांक्षी युग में आध्यात्मिक विराम। कार्य सौंपें, ध्यान बढ़ाएँ; अभी परिष्कृत पहचान आगामी कालों में अधिक चमकती है।"};
C.antar["sun-venus"]={en:"Surya–Shukra pairs power with grace — success in arts, luxury sectors, diplomacy and public charm. Relationships with women and creative partners prosper. Enjoy the limelight generously.",hi:"सूर्य–शुक्र शक्ति और लालित्य का युग्म है — कला, वैभव-क्षेत्रों, कूटनीति और जन-आकर्षण में सफलता। स्त्रियों और सृजन-साथियों से संबंध फलते हैं। प्रकाश-वृत्त का आनंद उदारता से लें।"};
})(typeof window!=='undefined'?window:global);

(function(g){var C=g.SD_CONTENT;
C.antar["moon-moon"]={en:"Chandra–Chandra doubles the tide of feeling — home, mother, public connection and inner life all flow strongly. Nourish and be nourished; travel near water refreshes. Keep one anchor routine when moods swell.",hi:"चंद्र–चंद्र भावों का ज्वार दोगुना करता है — घर, माता, जन-संपर्क और अंतर्जीवन प्रबल बहते हैं। पोषण दें और पाएँ; जल-तट की यात्रा ताज़ा करती है। भाव उमड़ें तो एक स्थिर नियम थामे रखें।"};
C.antar["moon-mars"]={en:"Chandra–Mangal turns feeling into action — property matters, family enterprises and brave decisions succeed. Emotions run hot; let exercise burn the excess and speak after the pause.",hi:"चंद्र–मंगल भावना को कर्म में बदलता है — भूमि-संपत्ति, पारिवारिक उद्यम और साहसी निर्णय सफल होते हैं। भाव तप्त रहते हैं; अतिरिक्त को व्यायाम में जलाएँ और ठहरकर बोलें।"};
C.antar["moon-rahu"]={en:"Chandra–Rahu stirs deep waters — imagination soars, foreign connections and mass appeal grow, but the mind can exaggerate fears at night. Ground with routine, mantra and honest confidants; the creativity is real gold.",hi:"चंद्र–राहु गहरे जल मथता है — कल्पना ऊँची उड़ती है, विदेश-संपर्क और जन-आकर्षण बढ़ते हैं, पर रात्रि में मन भय बढ़ा-चढ़ा सकता है। दिनचर्या, मंत्र और विश्वस्त जनों से स्थिर रहें; यह सृजनशीलता सच्चा स्वर्ण है।"};
C.antar["moon-jupiter"]={en:"Chandra–Guru is the blessed full-moon phase — optimism, family expansion, education and honourable gains flow together. Elders bless, the public trusts. Share your abundance; it is self-refilling now.",hi:"चंद्र–गुरु आशीर्वादित पूर्णिमा-काल है — आशा, परिवार-विस्तार, विद्या और मर्यादित लाभ साथ बहते हैं। बड़े आशीष देते हैं, जन विश्वास करते हैं। समृद्धि बाँटिए; यह अभी स्वयं भरती रहती है।"};
C.antar["moon-saturn"]={en:"Chandra–Shani cools the heart to strengthen it — responsibilities toward family and the vulnerable mature you. Loneliness, if felt, is a teacher not a verdict. Serve steadily; emotional bedrock forms for life.",hi:"चंद्र–शनि हृदय को शीतल कर सशक्त करता है — परिवार और असहायों के प्रति उत्तरदायित्व आपको परिपक्व करते हैं। एकाकीपन लगे तो वह शिक्षक है, निर्णय नहीं। स्थिर सेवा करें; जीवन भर की भाव-नींव बनती है।"};
C.antar["moon-mercury"]={en:"Chandra–Budha makes the mind quick and communicative — writing, trade, counselling and learning thrive. Public dealings sparkle with wit. Note ideas immediately; this period mints them nonstop.",hi:"चंद्र–बुध मन को चपल और संवादी करता है — लेखन, व्यापार, परामर्श और अध्ययन फलते हैं। जन-व्यवहार में बुद्धि चमकती है। विचार तुरंत लिखें; यह काल उन्हें अनवरत गढ़ता है।"};
C.antar["moon-ketu"]={en:"Chandra–Ketu turns the mind pilgrim — detachment from drama, taste for silence, flashes of intuition. Old emotional knots untie gently. Guard sleep and avoid overthinking; peace is the achievement here.",hi:"चंद्र–केतु मन को तीर्थयात्री बनाता है — प्रपंच से विरक्ति, मौन की रुचि, अंतर्ज्ञान की कौंध। पुरानी भाव-गाँठें सहज खुलती हैं। निद्रा की रक्षा करें, अति-चिंतन से बचें; शांति ही यहाँ की उपलब्धि है।"};
C.antar["moon-venus"]={en:"Chandra–Shukra is milk and honey — comforts, romance, vehicles, décor and family celebrations abound. Social charm peaks. Savour without excess and gift generously; sweetness shared is doubled.",hi:"चंद्र–शुक्र दूध और मधु का काल है — सुख, प्रणय, वाहन, गृह-शोभा और पारिवारिक उत्सव भरपूर। सामाजिक आकर्षण शिखर पर। अति के बिना रस लें और खुले हाथ भेंट दें; बाँटी मिठास दोगुनी होती है।"};
C.antar["moon-sun"]={en:"Chandra–Surya aligns heart with crown — family support meets official recognition; excellent for stepping into visible responsibility. Parents' health merits care. Lead warmly and the public follows.",hi:"चंद्र–सूर्य हृदय और मुकुट को एक करता है — पारिवारिक सहयोग और अधिकारिक मान साथ मिलते हैं; दृश्य उत्तरदायित्व सँभालने हेतु उत्तम। माता-पिता का स्वास्थ्य ध्यान चाहिए। स्नेह से नेतृत्व करें, जन साथ चलते हैं।"};
C.antar["mars-mars"]={en:"Mangal–Mangal is the forge at white heat — courage, competition, surgery-grade precision and land matters dominate. Victories come to the disciplined. Cool the spark daily: exercise, hydrate, pause before words.",hi:"मंगल–मंगल श्वेत-तप्त भट्ठी है — साहस, स्पर्धा, शल्य-सी सूक्ष्मता और भूमि-कार्य प्रधान रहते हैं। विजय अनुशासित को मिलती है। चिंगारी नित्य शीतल करें: व्यायाम, जल, बोलने से पहले विराम।"};
C.antar["mars-rahu"]={en:"Mangal–Rahu is rocket fuel — audacious ventures, technical leaps and sudden advances possible. Risk management is everything: verify partners, avoid shortcuts and speed-related hazards; then the sky opens.",hi:"मंगल–राहु रॉकेट-ईंधन है — दुस्साहसी उद्यम, तकनीकी छलाँग और आकस्मिक प्रगति संभव। जोखिम-प्रबंधन ही सब कुछ है: साथी परखें, शॉर्टकट और तीव्र-गति संकटों से बचें; फिर आकाश खुला है।"};
C.antar["mars-jupiter"]={en:"Mangal–Guru is the righteous warrior — bold action guided by wisdom wins property, position and respect. Legal and educational matters favour you. Fight only worthy battles; all of them, you win.",hi:"मंगल–गुरु धर्म-योद्धा काल है — ज्ञान-निर्देशित पराक्रम संपत्ति, पद और सम्मान जीतता है। विधिक और शैक्षिक कार्य पक्ष में रहते हैं। केवल योग्य युद्ध चुनें; वे सब आप जीतते हैं।"};
C.antar["mars-saturn"]={en:"Mangal–Shani is fire meeting iron — heavy workloads, tests of stamina, friction with structures. Yet steel is forged exactly here: persist without rage, rest without guilt, and emerge unbreakable.",hi:"मंगल–शनि अग्नि और लौह का मिलन है — भारी कार्यभार, सहनशक्ति की परीक्षा, ढाँचों से घर्षण। पर इस्पात यहीं गढ़ा जाता है: क्रोध बिना डटे रहें, अपराध-बोध बिना विश्राम लें, और अटूट होकर निकलें।"};
C.antar["mars-mercury"]={en:"Mangal–Budha weaponizes intellect — sharp analysis, technical writing, trading and debate succeed. Words can cut; aim them at problems, not people. Quick gains favour the prepared mind.",hi:"मंगल–बुध बुद्धि को शस्त्र बनाता है — तीक्ष्ण विश्लेषण, तकनीकी लेखन, व्यापार और शास्त्रार्थ सफल। शब्द काट सकते हैं; उन्हें समस्याओं पर साधें, व्यक्तियों पर नहीं। त्वरित लाभ तैयार मन को मिलते हैं।"};
C.antar["mars-ketu"]={en:"Mangal–Ketu is silent lightning — intense focus for research, martial arts, surgery or sadhana. Energy spikes unpredictably; structured routines and careful driving turn volatility into mastery.",hi:"मंगल–केतु मौन विद्युत है — शोध, युद्धकला, शल्य या साधना हेतु प्रचंड एकाग्रता। ऊर्जा अकस्मात् उछलती है; नियमित दिनचर्या और सावधान वाहन-चालन चंचलता को प्रभुता में बदलते हैं।"};
C.antar["mars-venus"]={en:"Mangal–Shukra heats romance and earnings — passion projects, property beautification and bold investments in pleasure pay off. Balance desire with devotion; commitment makes the fire golden.",hi:"मंगल–शुक्र प्रणय और अर्जन को गरमाता है — प्रिय-परियोजनाएँ, संपत्ति-सज्जा और सुख में साहसी निवेश फलते हैं। इच्छा को समर्पण से साधें; प्रतिबद्धता इस अग्नि को स्वर्णिम करती है।"};
C.antar["mars-sun"]={en:"Mangal–Surya is double fire commanding — leadership in crises, wins over rivals, honours from authority. Father and health need gentleness. March at the front, but let the heart stay soft inside the armour.",hi:"मंगल–सूर्य द्वि-अग्नि का आदेश है — संकटों में नेतृत्व, प्रतिद्वंद्वियों पर विजय, सत्ता से सम्मान। पिता और स्वास्थ्य कोमलता चाहते हैं। अग्रिम पंक्ति में चलें, पर कवच के भीतर हृदय कोमल रहे।"};
C.antar["mars-moon"]={en:"Mangal–Chandra churns emotion into enterprise — family property, home renovations and protective courage activate. Moods flare fast and fade fast; a daily walk keeps the inner lake calm.",hi:"मंगल–चंद्र भाव को उद्यम में मथता है — पारिवारिक संपत्ति, गृह-सुधार और रक्षक साहस सक्रिय होते हैं। भाव शीघ्र भड़कते-बुझते हैं; नित्य टहलना भीतर की झील शांत रखता है।"};
C.antar["rahu-rahu"]={en:"Rahu–Rahu is the great amplifier squared — foreign lands, technology, mass platforms and outsized ambitions dominate. Fortunes can multiply suddenly; so can illusions. Audit everything, keep dharma lit, ride the wave.",hi:"राहु–राहु महावर्धक का वर्ग है — विदेश, तकनीक, जन-मंच और विराट महत्वाकांक्षाएँ प्रधान। भाग्य अकस्मात् कई गुना हो सकता है; भ्रम भी। सब कुछ परखें, धर्म-दीप जलाए रखें, लहर पर सवार रहें।"};
C.antar["rahu-jupiter"]={en:"Rahu–Guru civilizes the storm — wise counsel channels vast ambition into legitimate expansion. Foreign education, publishing and big-institution dealings succeed. Gratitude to gurus keeps the genie benevolent.",hi:"राहु–गुरु आँधी को संस्कार देता है — विवेकपूर्ण मार्गदर्शन विराट महत्वाकांक्षा को वैध विस्तार देता है। विदेश-शिक्षा, प्रकाशन और बड़ी संस्थाओं के कार्य सफल। गुरुजनों के प्रति कृतज्ञता इस शक्ति को शुभ रखती है।"};
C.antar["rahu-saturn"]={en:"Rahu–Shani tests foundations under pressure — slow-burning challenges in work or reputation ask for scrupulous honesty and stamina. Cut clutter, honour every deadline; what survives this becomes permanent.",hi:"राहु–शनि दबाव में नींव परखता है — कार्य या कीर्ति की मंद-दहन चुनौतियाँ निष्कलंक ईमानदारी और सहनशक्ति माँगती हैं। अनावश्यक काटें, हर समय-सीमा निभाएँ; जो यह पार करे, वह स्थायी हो जाता है।"};
C.antar["rahu-mercury"]={en:"Rahu–Budha electrifies commerce and code — digital ventures, analytics, languages and networks explode with opportunity. Information is currency; verify sources and back up everything, then trade boldly.",hi:"राहु–बुध वाणिज्य और तकनीक में विद्युत भरता है — डिजिटल उद्यम, विश्लेषण, भाषाएँ और नेटवर्क अवसरों से फूटते हैं। सूचना ही मुद्रा है; स्रोत परखें, सब सुरक्षित रखें, फिर निर्भय व्यापार करें।"};
C.antar["rahu-ketu"]={en:"Rahu–Ketu spans the whole axis — desires and detachment wrestle; sudden reversals possible in direction of life. Decide little, meditate much, keep health screenings current; equilibrium returns transformed.",hi:"राहु–केतु पूरे अक्ष को फैलाता है — इच्छा और वैराग्य में द्वंद्व; जीवन-दिशा में आकस्मिक मोड़ संभव। निर्णय कम, ध्यान अधिक; स्वास्थ्य-जाँच नियमित रखें; संतुलन रूपांतरित होकर लौटता है।"};
C.antar["rahu-venus"]={en:"Rahu–Shukra intoxicates with worldly sweetness — fame, luxury, cinema-like romance and windfalls beckon. Enjoy consciously: contracts read twice, relationships chosen for character; then this is one of life's richest chapters.",hi:"राहु–शुक्र सांसारिक माधुर्य से मदमस्त करता है — प्रसिद्धि, वैभव, स्वप्निल प्रणय और अप्रत्याशित लाभ बुलाते हैं। सजग होकर रस लें: अनुबंध दो बार पढ़ें, संबंध चरित्र देखकर चुनें; तब यह जीवन का समृद्धतम अध्याय बनता है।"};
C.antar["rahu-sun"]={en:"Rahu–Surya spotlights identity — political or organizational visibility rises, with tests of ego and authenticity. Fathers and mentors need warmth. Be transparently yourself; masks cost more than they earn now.",hi:"राहु–सूर्य पहचान पर प्रकाश डालता है — राजनीतिक या संगठनात्मक प्रसिद्धि बढ़ती है, संग अहं और प्रामाणिकता की परीक्षाएँ। पिता-गुरुजन स्नेह चाहते हैं। पारदर्शी स्वयं रहें; मुखौटे अभी लाभ से महँगे पड़ते हैं।"};
C.antar["rahu-moon"]={en:"Rahu–Chandra magnifies the mind — mass appeal, vivid creativity, and sensitivity that can tip into worry. Anchor with mother-figures, moonstone-calm routines and japa; the public connection built now is vast.",hi:"राहु–चंद्र मन को विशाल करता है — जन-आकर्षण, सजीव सृजनशीलता, और संवेदना जो चिंता में ढल सकती है। मातृ-स्वरूपों, शांत दिनचर्या और जप से स्थिर रहें; अभी बना जन-जुड़ाव विराट होता है।"};
C.antar["rahu-mars"]={en:"Rahu–Mangal is high-voltage daring — breakthroughs in technology, competition and land dealings for the disciplined; hazards for the hasty. Helmet on, contracts checked, temper cooled — then charge.",hi:"राहु–मंगल उच्च-विभव दुस्साहस है — अनुशासितों को तकनीक, स्पर्धा और भूमि-कार्य में महाविजय; उतावलों को संकट। सुरक्षा पहनें, अनुबंध जाँचें, क्रोध ठंडा करें — फिर धावा बोलें।"};
})(typeof window!=='undefined'?window:global);

(function(g){var C=g.SD_CONTENT;
C.antar["jupiter-jupiter"]={en:"Guru–Guru is grace at its fullest — wisdom, wealth, children, teachers and honour expand together. Whatever you plant now grows for decades. Teach, publish, bless and build institutions; the universe co-signs.",hi:"गुरु–गुरु कृपा का पूर्ण रूप है — ज्ञान, धन, संतान, गुरुजन और मान साथ बढ़ते हैं। अभी बोया दशकों फलता है। सिखाइए, प्रकाशित कीजिए, आशीर्वाद दीजिए, संस्थाएँ गढ़िए; सृष्टि स्वयं हस्ताक्षर करती है।"};
C.antar["jupiter-saturn"]={en:"Guru–Shani weds wisdom to discipline — slow, honourable construction of career and legacy. Justice matters conclude fairly. Effort feels heavy but every brick is permanent; elders' advice is gold now.",hi:"गुरु–शनि ज्ञान और अनुशासन का विवाह है — पद और विरासत का धीमा, मर्यादित निर्माण। न्याय-कार्य उचित परिणति पाते हैं। श्रम भारी लगे पर हर ईंट स्थायी है; बड़ों का परामर्श अभी स्वर्ण है।"};
C.antar["jupiter-mercury"]={en:"Guru–Budha unites the two teachers — study, writing, commerce and counsel flourish brilliantly. Certifications, publications and profitable ideas arrive in streams. Speak and write daily; each word compounds.",hi:"गुरु–बुध दोनों आचार्यों का मिलन है — अध्ययन, लेखन, वाणिज्य और परामर्श उज्ज्वल फलते हैं। प्रमाणपत्र, प्रकाशन और लाभकारी विचार धाराओं में आते हैं। नित्य बोलें-लिखें; हर शब्द चक्रवृद्धि होता है।"};
C.antar["jupiter-ketu"]={en:"Guru–Ketu turns wisdom inward — pilgrimage, moksha-oriented study and quiet philanthropy call. Material growth pauses politely while spiritual assets multiply. A guru's glance now can change everything.",hi:"गुरु–केतु ज्ञान को अंतर्मुखी करता है — तीर्थ, मोक्ष-केंद्रित अध्ययन और मौन परोपकार पुकारते हैं। भौतिक वृद्धि विनम्र विराम लेती है, आध्यात्मिक संपदा कई गुना होती है। गुरु की एक दृष्टि अभी सब बदल सकती है।"};
C.antar["jupiter-venus"]={en:"Guru–Shukra showers double benefic rain — marriage, children, vehicles, wealth and refined joys are classically promised. Give dāna generously and celebrate ethically; this is harvest weather.",hi:"गुरु–शुक्र द्विशुभ वर्षा है — विवाह, संतान, वाहन, धन और परिष्कृत आनंद के शास्त्रीय वचन। उदार दान दें, मर्यादित उत्सव मनाएँ; यह फ़सल का मौसम है।"};
C.antar["jupiter-sun"]={en:"Guru–Surya seats you among the respected — government favour, awards, fatherly blessings and roles of dignified authority. Lead as a mentor-king: generous, principled, visibly fair.",hi:"गुरु–सूर्य आपको प्रतिष्ठितों में आसन देता है — शासकीय कृपा, सम्मान, पितृ-आशीर्वाद और गरिमामय अधिकार की भूमिकाएँ। गुरु-राजा बनकर नेतृत्व करें: उदार, सिद्धांतनिष्ठ, प्रत्यक्ष न्यायप्रिय।"};
C.antar["jupiter-moon"]={en:"Guru–Chandra fills the heart's granary — domestic happiness, public trust, and gains through nurture and teaching. Mother's blessings power this phase. Emotional generosity returns tenfold.",hi:"गुरु–चंद्र हृदय का भंडार भरता है — गृह-सुख, जन-विश्वास, और पोषण-शिक्षण से लाभ। माता का आशीर्वाद इस चरण की शक्ति है। भाव-उदारता दस गुना लौटती है।"};
C.antar["jupiter-mars"]={en:"Guru–Mangal is dharma with a sword — decisive expansion, property acquisition, victories in rightful disputes. Energy is high and blessed; act boldly on well-counselled plans.",hi:"गुरु–मंगल खड्गधारी धर्म है — निर्णायक विस्तार, संपत्ति-प्राप्ति, न्यायोचित विवादों में विजय। ऊर्जा उच्च और आशीर्वादित है; सुपरामर्शित योजनाओं पर साहसपूर्वक कार्य करें।"};
C.antar["jupiter-rahu"]={en:"Guru–Rahu stretches fortune across borders — unconventional growth, foreign gains and large audiences, with occasional tests of judgment. Keep one wise elder in every big decision; then expansion stays golden.",hi:"गुरु–राहु भाग्य को सीमाओं के पार फैलाता है — अपरंपरागत वृद्धि, विदेश-लाभ और विशाल जन-समूह, संग विवेक की यदा-कदा परीक्षाएँ। हर बड़े निर्णय में एक ज्ञानी वृद्ध रखें; विस्तार स्वर्णिम रहेगा।"};
C.antar["saturn-saturn"]={en:"Shani–Shani is the deep foundation pour — maximum discipline, minimum glamour, permanent results. Health, joints and routines need care. What you patiently maintain now becomes your old-age fortress.",hi:"शनि–शनि गहरी नींव की ढलाई है — अधिकतम अनुशासन, न्यूनतम चमक, स्थायी परिणाम। स्वास्थ्य, संधियों और दिनचर्या का ध्यान रखें। अभी धैर्य से सँभाला हुआ ही वृद्धावस्था का दुर्ग बनता है।"};
C.antar["saturn-mercury"]={en:"Shani–Budha systematizes intellect — accounting, engineering, documentation and skill-certification thrive. Slow study becomes deep mastery. Speak less, deliver more; reputation compounds quietly.",hi:"शनि–बुध बुद्धि को व्यवस्थित करता है — लेखांकन, अभियांत्रिकी, प्रलेखन और कौशल-प्रमाणन फलते हैं। धीमा अध्ययन गहरी प्रभुता बनता है। कम बोलें, अधिक करें; कीर्ति मौन चक्रवृद्धि होती है।"};
C.antar["saturn-ketu"]={en:"Shani–Ketu strips to essentials — solitude, austerity and karmic clearing. Excellent for long sadhana, debt-closure and simplifying life. Loneliness transmutes into self-sufficiency; honour the process.",hi:"शनि–केतु सार तक छाँटता है — एकांत, तप और कर्म-शुद्धि। दीर्घ साधना, ऋण-समापन और जीवन-सरलीकरण हेतु उत्तम। एकाकीपन आत्मनिर्भरता में बदलता है; इस प्रक्रिया का सम्मान करें।"};
C.antar["saturn-venus"]={en:"Shani–Shukra matures love and wealth — enduring relationships, disciplined savings and classical arts flourish. Pleasures simplify and deepen. Commit fully to person and craft; time itself becomes your ally.",hi:"शनि–शुक्र प्रेम और धन को परिपक्व करता है — स्थायी संबंध, अनुशासित बचत और शास्त्रीय कलाएँ फलती हैं। सुख सरल होकर गहराते हैं। व्यक्ति और कला के प्रति पूर्ण समर्पित रहें; काल स्वयं मित्र बन जाता है।"};
C.antar["saturn-sun"]={en:"Shani–Surya negotiates duty with dignity — friction with authority possible, but flawless work makes you indispensable. Care for father and heart-health. Quiet excellence outshines loud claims.",hi:"शनि–सूर्य कर्तव्य और गरिमा का संधि-काल है — सत्ता से घर्षण संभव, पर निष्कलंक कार्य आपको अनिवार्य बना देता है। पिता और हृदय-स्वास्थ्य का ध्यान रखें। मौन श्रेष्ठता ऊँचे दावों से अधिक चमकती है।"};
C.antar["saturn-moon"]={en:"Shani–Chandra weathers the heart — emotional loads, family duties and tests of morale. Do not isolate: warm company, sunlight and seva dissolve the grey. Inner steel forms that nothing later bends.",hi:"शनि–चंद्र हृदय को तपाता है — भावनात्मक भार, पारिवारिक कर्तव्य और मनोबल की परीक्षाएँ। अकेले न पड़ें: स्नेही संग, धूप और सेवा धूसरता घोल देते हैं। भीतर वह इस्पात बनता है जिसे आगे कुछ नहीं मोड़ता।"};
C.antar["saturn-mars"]={en:"Shani–Mangal grinds iron on stone — heavy labour, obstacles, and the exact pressure that creates diamonds. Avoid conflicts and rash risks; convert force into craft. Survivors of this period fear nothing after.",hi:"शनि–मंगल लौह को पत्थर पर घिसता है — कठोर श्रम, बाधाएँ, और वही दबाव जो हीरे गढ़ता है। संघर्ष और उतावले जोखिम टालें; बल को शिल्प में बदलें। इस काल के पार निकले फिर किसी से नहीं डरते।"};
C.antar["saturn-rahu"]={en:"Shani–Rahu tests integrity under ambition — tempting shortcuts appear precisely when discipline matters most. Choose the slow lawful road every time; hidden audits end in your favour and elevation follows.",hi:"शनि–राहु महत्वाकांक्षा में सत्यनिष्ठा परखता है — प्रलोभक शॉर्टकट ठीक तब दिखते हैं जब अनुशासन सर्वाधिक आवश्यक है। हर बार धीमा वैध मार्ग चुनें; गुप्त परीक्षाएँ आपके पक्ष में समाप्त होती हैं और उत्थान आता है।"};
C.antar["saturn-jupiter"]={en:"Shani–Guru rewards the patient student — structured learning, mentorship and principled career moves bear durable fruit. Justice and institutions favour you. Build slowly what children will inherit.",hi:"शनि–गुरु धैर्यवान विद्यार्थी को फल देता है — व्यवस्थित अध्ययन, गुरु-मार्गदर्शन और सिद्धांतनिष्ठ पद-चालन स्थायी फल लाते हैं। न्याय और संस्थाएँ पक्ष में रहती हैं। वह धीरे गढ़िए जो संततियाँ पाएँगी।"};
C.antar["mercury-mercury"]={en:"Budha–Budha is the mind at play — ideas, deals, languages and networks multiply joyfully. Perfect for launches in writing, trade and analytics. Finish what you start; brilliance needs delivery.",hi:"बुध–बुध क्रीड़ारत बुद्धि है — विचार, सौदे, भाषाएँ और संपर्क आनंदपूर्वक बहुगुणित होते हैं। लेखन, व्यापार और विश्लेषण के शुभारंभ हेतु आदर्श। आरंभ किया पूर्ण करें; प्रतिभा को प्रस्तुति चाहिए।"};
C.antar["mercury-ketu"]={en:"Budha–Ketu quiets the chatter into insight — research, diagnostics, mantra-shastra and puzzles of every kind open. Communication may misfire; write precisely, confirm twice, and trust the flashes.",hi:"बुध–केतु कोलाहल को अंतर्दृष्टि में शांत करता है — शोध, निदान, मंत्र-शास्त्र और हर प्रकार की पहेलियाँ खुलती हैं। संवाद चूक सकता है; सटीक लिखें, दो बार पुष्टि करें, और अंतःस्फुरण पर विश्वास रखें।"};
C.antar["mercury-venus"]={en:"Budha–Shukra sweetens every transaction — arts, design, luxury trade and pleasant negotiations prosper. Friendships turn profitable and profits turn friendly. Craft beauty that sells and truth that charms.",hi:"बुध–शुक्र हर व्यवहार को मधुर करता है — कला, डिज़ाइन, वैभव-व्यापार और सौहार्दपूर्ण वार्ताएँ फलती हैं। मित्रता लाभ बनती है, लाभ मैत्री। ऐसा सौंदर्य गढ़ें जो बिके, ऐसा सत्य जो मोह ले।"};
C.antar["mercury-sun"]={en:"Budha–Surya crowns the analyst — administrative wins, exam success, official contracts and eloquent authority. Present your work upward; the throne is reading your reports now.",hi:"बुध–सूर्य विश्लेषक का राज्याभिषेक है — प्रशासनिक विजय, परीक्षा-सफलता, अधिकारिक अनुबंध और प्रभावी वक्तृत्व। कार्य ऊपर तक प्रस्तुत करें; सिंहासन अभी आपके प्रतिवेदन पढ़ रहा है।"};
C.antar["mercury-moon"]={en:"Budha–Chandra makes thought flow like water — counselling, teaching, public writing and trade in essentials thrive. The mind is quick and kind together. Publish freely; the audience is listening.",hi:"बुध–चंद्र विचार को जल-सा प्रवाह देता है — परामर्श, शिक्षण, जन-लेखन और आवश्यक वस्तुओं का व्यापार फलता है। मन चपल और करुण साथ-साथ है। खुलकर प्रकाशित करें; श्रोता सुन रहे हैं।"};
C.antar["mercury-mars"]={en:"Budha–Mangal debates to win — technical execution, sharp negotiations and competitive analytics succeed. Guard against cutting words and hasty signatures; precision plus courtesy is unbeatable.",hi:"बुध–मंगल जीतने के लिए तर्क करता है — तकनीकी निष्पादन, पैनी वार्ताएँ और स्पर्धात्मक विश्लेषण सफल। कटु शब्द और उतावले हस्ताक्षर से बचें; सूक्ष्मता संग शिष्टता अजेय है।"};
C.antar["mercury-rahu"]={en:"Budha–Rahu hacks the possible — digital ventures, viral communication, foreign trade and clever systems bring outsized returns. Information hygiene is vital: verify, encrypt, document. Then scale fearlessly.",hi:"बुध–राहु संभव की सीमा तोड़ता है — डिजिटल उद्यम, विस्तृत-प्रसार संवाद, विदेश-व्यापार और चतुर प्रणालियाँ विशाल फल देती हैं। सूचना-शुद्धि अनिवार्य: परखें, सुरक्षित रखें, प्रलेखित करें। फिर निर्भय विस्तार करें।"};
C.antar["mercury-jupiter"]={en:"Budha–Guru graduates the merchant into the sage — teaching, publishing, consultancy and honest commerce flourish with blessings. Wisdom becomes income. Mentor juniors; your knowledge-lineage begins here.",hi:"बुध–गुरु व्यापारी को आचार्य बनाता है — शिक्षण, प्रकाशन, परामर्श और सद्-वाणिज्य आशीर्वाद सहित फलते हैं। ज्ञान आय बनता है। कनिष्ठों का मार्गदर्शन करें; आपकी विद्या-परंपरा यहीं आरंभ होती है।"};
C.antar["mercury-saturn"]={en:"Budha–Shani audits the intellect — detailed work, compliance, long documents and certifications dominate. Slow accuracy beats fast brilliance now. Systems built in this period run for decades.",hi:"बुध–शनि बुद्धि का लेखा-परीक्षण है — सूक्ष्म कार्य, अनुपालन, दीर्घ प्रलेख और प्रमाणन प्रधान रहते हैं। धीमी शुद्धता अभी तीव्र चतुराई से श्रेष्ठ है। इस काल में बनी प्रणालियाँ दशकों चलती हैं।"};
})(typeof window!=='undefined'?window:global);
