// SHUBH DIN — Kundli Report Content Library (v1, EN + HI)
// Text blocks keyed to engine outputs. Written per the K8 psychology playbook:
// strengths-first, warm second person, hedged cautions always paired with sadhana.
(function (global) {
  'use strict';
  var C = {};

  // ---- Birth Nakshatra personality (27) ----
  C.nakshatra = [
  { en: "Born under Ashvini, you carry the energy of new beginnings — quick to act, quick to heal, and quick to help. People notice your youthful enthusiasm and your gift for getting things started. Practise patience with slower souls; finishing what you begin multiplies your natural brilliance.",
    hi: "अश्विनी नक्षत्र में जन्मे आप नई शुरुआत की ऊर्जा लेकर आए हैं — तुरंत कार्य करने वाले, शीघ्र स्वस्थ होने वाले और सहायता के लिए सदा तत्पर। आपकी युवा-सी स्फूर्ति सबका ध्यान खींचती है। धैर्य का अभ्यास और आरंभ किए कार्य को पूर्ण करना आपकी प्रतिभा को कई गुना कर देता है।" },
  { en: "Bharani gives you rare inner strength — you can carry responsibilities that would exhaust others, and you transform every hardship into wisdom. Loyalty runs deep in you. Guard against taking on too much silently; sharing your burden is strength, not weakness.",
    hi: "भरणी आपको दुर्लभ आंतरिक शक्ति देती है — आप वे उत्तरदायित्व सहज उठा लेते हैं जो औरों को थका दें, और हर कठिनाई को अनुभव में बदल देते हैं। निष्ठा आपके स्वभाव में है। सब कुछ अकेले चुपचाप उठाने से बचें; अपनों से बाँट लेना भी शक्ति ही है।" },
  { en: "Krittika blesses you with a sharp, purifying intellect — you see through pretence instantly and speak truth with courage. You set high standards and inspire others to rise. Let warmth soften your fire; your honesty lands best when wrapped in kindness.",
    hi: "कृत्तिका आपको तीक्ष्ण, शुद्ध करने वाली बुद्धि देती है — आप दिखावे को तुरंत पहचान लेते हैं और साहस से सत्य कहते हैं। आपके ऊँचे मापदंड औरों को भी ऊपर उठाते हैं। अपनी अग्नि में स्नेह मिलाइए; करुणा के साथ कहा गया सत्य सबसे गहरा उतरता है।" },
  { en: "Rohini makes you naturally magnetic — creative, steady, and deeply appreciative of beauty and comfort. Things grow under your care: family, savings, gardens, relationships. Watch attachment to comfort; a little discipline keeps your abundance flowing.",
    hi: "रोहिणी आपको सहज आकर्षण देती है — रचनात्मक, स्थिर और सौंदर्य के सच्चे पारखी। आपके स्पर्श से चीज़ें फलती-फूलती हैं: परिवार, बचत, संबंध। सुख-सुविधा से अधिक मोह से सावधान रहें; थोड़ा संयम आपकी समृद्धि को सदा प्रवाहित रखता है।" },
  { en: "Mrigashira gives you a seeker's heart — curious, gentle, always searching for something finer. You learn quickly and converse beautifully. Restlessness is your only shadow; when you commit to one path deeply, you find the very treasure you were seeking.",
    hi: "मृगशिरा आपको खोजी हृदय देता है — जिज्ञासु, सौम्य, सदा किसी श्रेष्ठ वस्तु की तलाश में। आप शीघ्र सीखते हैं और मधुर संवाद करते हैं। चंचलता ही एकमात्र छाया है; जब आप एक मार्ग पर गहराई से टिकते हैं, वही खज़ाना मिल जाता है जिसकी खोज थी।" },
  { en: "Ardra grants you intensity and intelligence that thrive in storms — you handle crises that overwhelm others and emerge renewed. Your empathy for suffering is profound. Channel the storm through steady routines; calm waters let your genius shine longest.",
    hi: "आर्द्रा आपको वह तीव्रता और बुद्धि देती है जो तूफ़ानों में निखरती है — आप उन संकटों को संभाल लेते हैं जो औरों को तोड़ दें, और नए होकर निकलते हैं। दुख के प्रति आपकी संवेदना गहरी है। नियमित दिनचर्या से इस ऊर्जा को दिशा दें; शांत जल में आपकी प्रतिभा सबसे देर तक चमकती है।" },
  { en: "Punarvasu is the star of return and renewal — no setback keeps you down for long. You rebuild, restore, and bring hope wherever you go. Generous and philosophical, you gather goodwill everywhere. Trust your comeback power; it is your life's signature.",
    hi: "पुनर्वसु पुनरागमन और नवीनीकरण का नक्षत्र है — कोई भी विफलता आपको अधिक समय तक रोक नहीं पाती। आप फिर बनाते हैं, फिर सँवारते हैं और जहाँ जाते हैं आशा ले जाते हैं। उदार और चिंतनशील स्वभाव सबका स्नेह जीतता है। अपनी वापसी की शक्ति पर विश्वास रखें; यही आपके जीवन की पहचान है।" },
  { en: "Pushya, the most nourishing nakshatra, makes you a natural protector — dependable, dutiful, and quietly powerful. People instinctively trust you with what they value most. Remember to nourish yourself too; your care multiplies when your own cup is full.",
    hi: "पुष्य, सबसे पोषक नक्षत्र, आपको स्वाभाविक संरक्षक बनाता है — विश्वसनीय, कर्तव्यनिष्ठ और शांत शक्ति से भरा। लोग सहज ही अपनी प्रिय वस्तुएँ आपको सौंप देते हैं। स्वयं का पोषण भी करें; जब आपका पात्र भरा रहता है, आपकी सेवा कई गुना फलती है।" },
  { en: "Ashlesha gives you penetrating insight — you read people and situations at a depth few possess, and your focus, once locked, is unbreakable. Use this power to heal and guide. Release grudges quickly; forgiveness keeps your remarkable mind luminous.",
    hi: "आश्लेषा आपको भेदक अंतर्दृष्टि देती है — आप व्यक्तियों और परिस्थितियों को उस गहराई तक पढ़ लेते हैं जहाँ कम ही पहुँचते हैं, और एक बार लगी एकाग्रता अटूट होती है। इस शक्ति से मार्गदर्शन कीजिए। मन की गाँठें शीघ्र खोल दें; क्षमा आपके विलक्षण मन को उजला रखती है।" },
  { en: "Magha connects you to noble lineage and leadership — dignity comes naturally, and you honour traditions while carrying real authority. Others look to you in important moments. Lead with humility and gratitude to elders; that is where your throne truly stands.",
    hi: "मघा आपको कुल-गौरव और नेतृत्व से जोड़ती है — गरिमा आपमें सहज है, आप परंपराओं का सम्मान करते हुए वास्तविक अधिकार धारण करते हैं। महत्वपूर्ण क्षणों में लोग आपकी ओर देखते हैं। विनम्रता और पितरों-बड़ों के प्रति कृतज्ञता के साथ नेतृत्व करें; आपका सिंहासन वहीं स्थिर है।" },
  { en: "Purva Phalguni fills you with warmth, charm, and the art of enjoying life — you create joy around you and love generously. Creativity and relationships flourish in your presence. Balance pleasure with purpose; your charisma achieves wonders when pointed at a goal.",
    hi: "पूर्वा फाल्गुनी आपको उष्णता, आकर्षण और जीवन का आनंद लेने की कला देती है — आप अपने चारों ओर उत्सव रचते हैं और खुले हृदय से प्रेम करते हैं। रचनात्मकता और संबंध आपके संग खिलते हैं। आनंद के साथ उद्देश्य जोड़िए; लक्ष्य की ओर मुड़ा आपका आकर्षण चमत्कार करता है।" },
  { en: "Uttara Phalguni gives you the gift of reliable friendship and honourable dealing — people build their plans on your word, and your generosity uplifts many. Partnerships prosper with you. Keep clear boundaries; helping wisely serves more than helping endlessly.",
    hi: "उत्तरा फाल्गुनी आपको विश्वसनीय मित्रता और सम्मानपूर्ण व्यवहार का वरदान देती है — लोग आपके वचन पर योजनाएँ बनाते हैं, आपकी उदारता अनेकों को ऊपर उठाती है। साझेदारियाँ आपके साथ फलती हैं। सीमाएँ स्पष्ट रखें; विवेकपूर्ण सहायता अनंत सहायता से अधिक फलदायी है।" },
  { en: "Hasta places skill directly in your hands — craftsmanship, healing, precise work, and clever wit all come naturally. What you touch improves. Trust your hands-on judgment over second-hand opinions, and keep a light heart; your humour is medicine for many.",
    hi: "हस्त नक्षत्र कौशल सीधे आपके हाथों में रखता है — शिल्प, सेवा-सुश्रूषा, सूक्ष्म कार्य और चतुर वाणी आपमें सहज है। जिसे आप छूते हैं वह निखर जाता है। दूसरों की सुनी-सुनाई राय से अधिक अपने हाथ के अनुभव पर भरोसा रखें, और मन हल्का रखें; आपका हास्य कई हृदयों की औषधि है।" },
  { en: "Chitra makes you a born designer of life — you see the finished masterpiece where others see raw material, and you have the courage to build it. Style, structure, and brilliance mark your work. Accept imperfect first drafts; masterpieces are polished, not born.",
    hi: "चित्रा आपको जीवन का जन्मजात शिल्पी बनाती है — जहाँ अन्य कच्चा माल देखते हैं, आप बनी हुई उत्कृष्ट कृति देख लेते हैं, और उसे गढ़ने का साहस रखते हैं। शैली, संरचना और तेज आपके कार्य की पहचान है। पहले प्रयास की अपूर्णता स्वीकारें; कृतियाँ जन्म से नहीं, तराशने से महान बनती हैं।" },
  { en: "Swati gives you independence like the free wind — adaptable, diplomatic, and self-made. You flourish when given space, and you negotiate beautifully. Root your freedom in a few firm commitments; the wind achieves most when it fills a chosen sail.",
    hi: "स्वाति आपको मुक्त पवन-सी स्वतंत्रता देती है — लचीले, कूटनीति में कुशल और स्वयं-निर्मित। खुला आकाश मिलते ही आप खिल उठते हैं और संवाद में संतुलन साध लेते हैं। अपनी स्वतंत्रता को कुछ दृढ़ संकल्पों से जोड़िए; पवन तभी सर्वाधिक सिद्ध करती है जब चुनी हुई पाल में भरती है।" },
  { en: "Vishakha grants you focused ambition — once you fix a goal, obstacles become fuel, and your persistence is legendary among those who know you. Victory follows you in stages. Celebrate milestones and companions along the way; the summit is sweeter shared.",
    hi: "विशाखा आपको लक्ष्य-केंद्रित महत्वाकांक्षा देती है — लक्ष्य निश्चित होते ही बाधाएँ ईंधन बन जाती हैं, आपकी लगन आपके परिचितों में प्रसिद्ध है। विजय चरणों में आपके पीछे चलती है। मार्ग के पड़ावों और साथियों का उत्सव मनाइए; बाँटा हुआ शिखर अधिक मधुर होता है।" },
  { en: "Anuradha is the star of devotion and friendship across boundaries — you build bridges where others see walls, and your loyalty in difficult times is your crown. Success often comes through alliances. Honour your own needs too; devotion includes the self.",
    hi: "अनुराधा भक्ति और सीमाओं के पार मित्रता का नक्षत्र है — जहाँ अन्य दीवारें देखते हैं, आप सेतु बनाते हैं, और कठिन समय की आपकी निष्ठा ही आपका मुकुट है। सफलता प्रायः सहयोग से आती है। अपनी आवश्यकताओं का भी मान रखें; भक्ति में स्वयं भी सम्मिलित है।" },
  { en: "Jyeshtha gives you the elder's seat — protective authority, sharp strategy, and the courage to stand alone for what is right. People seek your shelter in storms. Wear seniority lightly and mentor generously; your legacy is the people you raise.",
    hi: "ज्येष्ठा आपको ज्येष्ठ का आसन देती है — रक्षक अधिकार, पैनी रणनीति और उचित के लिए अकेले खड़े होने का साहस। संकट में लोग आपकी छाया खोजते हैं। बड़प्पन को सहजता से धारण करें और खुले मन से मार्गदर्शन दें; आपकी विरासत वे लोग हैं जिन्हें आप ऊपर उठाते हैं।" },
  { en: "Mula reaches for the root of everything — you are a truth-digger, unafraid of deep questions and fresh starts. Superficial answers never satisfy you. This depth is rare wealth; pace your transformations gently so loved ones can travel with you.",
    hi: "मूल हर वस्तु की जड़ तक पहुँचता है — आप सत्य के खोजी हैं, गहरे प्रश्नों और नई शुरुआतों से निर्भय। सतही उत्तर आपको कभी संतुष्ट नहीं करते। यह गहराई दुर्लभ संपदा है; अपने परिवर्तनों की गति सौम्य रखें ताकि प्रियजन साथ चल सकें।" },
  { en: "Purva Ashadha gives you invincible optimism — you declare bold visions and carry others on the tide of your confidence. Water finds a way, and so do you. Verify details before the big leap; then your victories become unstoppable and lasting.",
    hi: "पूर्वाषाढ़ा आपको अजेय आशावाद देती है — आप साहसिक स्वप्न घोषित करते हैं और अपने आत्मविश्वास की लहर पर औरों को भी ले चलते हैं। जल मार्ग खोज ही लेता है, और आप भी। बड़ी छलाँग से पहले विवरण परख लें; फिर आपकी विजयें अजेय और स्थायी हो जाती हैं।" },
  { en: "Uttara Ashadha grants victory that endures — you win not by speed but by unshakeable integrity and patient effort. Leaders and institutions trust you naturally. Your word is your monument; keep choosing the long right road over the short clever one.",
    hi: "उत्तराषाढ़ा स्थायी विजय देती है — आप गति से नहीं, अडिग सत्यनिष्ठा और धैर्यपूर्ण परिश्रम से जीतते हैं। नेतृत्व और संस्थाएँ आप पर सहज विश्वास करती हैं। आपका वचन ही आपका स्मारक है; छोटे चतुर मार्ग की जगह लंबा सही मार्ग चुनते रहिए।" },
  { en: "Shravana is the star of sacred listening — you learn from everything and everyone, and your counsel carries the weight of true understanding. Knowledge flows to you and through you. Protect quiet time for study and reflection; it is your power source.",
    hi: "श्रवण पवित्र श्रवण का नक्षत्र है — आप हर व्यक्ति और अनुभव से सीखते हैं, आपके परामर्श में सच्ची समझ का भार होता है। ज्ञान आपकी ओर बहता है और आपसे होकर बँटता है। अध्ययन और चिंतन के लिए एकांत समय सुरक्षित रखें; वही आपकी ऊर्जा का स्रोत है।" },
  { en: "Dhanishtha gives you rhythm and prosperity — music, timing, teamwork, and wealth-building all respond to your touch. You perform best with an audience or a team. Stay generous as you rise; shared prosperity is the melody that never fades.",
    hi: "धनिष्ठा आपको लय और समृद्धि देती है — संगीत, समय की समझ, टीम-भावना और धन-संचय, सब आपके स्पर्श से सधते हैं। दर्शकों या दल के संग आप सर्वश्रेष्ठ करते हैं। ऊँचाई पर भी उदार रहिए; बाँटी हुई समृद्धि वह राग है जो कभी नहीं थमता।" },
  { en: "Shatabhisha, the hundred healers, gives you the gift of solving what others call incurable — in technology, medicine, or human hearts. You value truth and solitude. Let trusted people in; the healer heals deepest in genuine connection.",
    hi: "शतभिषा, सौ वैद्यों का नक्षत्र, आपको वह वरदान देता है कि जिसे लोग असाध्य कहें, आप उसका समाधान खोज लें — तकनीक में, चिकित्सा में या मानव हृदयों में। आप सत्य और एकांत के प्रेमी हैं। विश्वस्त जनों को निकट आने दें; सच्चे जुड़ाव में ही चिकित्सक की गहनतम चिकित्सा होती है।" },
  { en: "Purva Bhadrapada gives you visionary fire — you sense higher purpose behind events and can inspire radical positive change. Your intensity is transformative. Ground your fire in daily sadhana; a steady lamp illumines more than a flare.",
    hi: "पूर्वाभाद्रपद आपको दूरदर्शी अग्नि देता है — घटनाओं के पीछे का उच्च प्रयोजन आप भाँप लेते हैं और गहरे शुभ परिवर्तन की प्रेरणा बन सकते हैं। आपकी तीव्रता रूपांतरकारी है। इस अग्नि को नित्य साधना में स्थिर करें; टिमटिमाती लौ से अधिक प्रकाश स्थिर दीपक देता है।" },
  { en: "Uttara Bhadrapada grants oceanic depth and calm — your patience outlasts every storm, and people find peace simply sitting near you. Wisdom matures early in you. Share it gently and often; your stillness is a gift this restless world needs.",
    hi: "उत्तराभाद्रपद सागर-सी गहराई और शांति देता है — आपका धैर्य हर तूफ़ान से लंबा है, लोग आपके निकट बैठकर ही शांति पा लेते हैं। ज्ञान आपमें शीघ्र परिपक्व होता है। उसे सहजता से बाँटते रहिए; आपकी स्थिरता इस अशांत संसार के लिए वरदान है।" },
  { en: "Revati, the final nakshatra, makes you a guide of safe journeys — nurturing, prosperous, and instinctively protective of the vulnerable. Completion is your art: you finish, you fulfil, you deliver people home. Guard your soft heart with wise company.",
    hi: "रेवती, अंतिम नक्षत्र, आपको सुरक्षित यात्राओं का पथ-प्रदर्शक बनाता है — पालक, समृद्ध और निर्बल के सहज रक्षक। पूर्णता आपकी कला है: आप कार्य पूर्ण करते हैं, वचन निभाते हैं, लोगों को उनके गंतव्य तक पहुँचाते हैं। अपने कोमल हृदय की रक्षा सत्संग से कीजिए।" }
  ];

  global.SD_CONTENT = C;
})(typeof window !== 'undefined' ? window : global);

// ---- Lagna personality (12), appended ----
(function(g){var C=g.SD_CONTENT;
C.lagna=[
  { en: "With Mesha rising, you meet life head-on — courageous, direct, and first to act when others hesitate. Leadership sits naturally on you. Channel the fire into one mission at a time, and your victories arrive faster than your impatience.", hi: "मेष लग्न के साथ आप जीवन का सामना सीधे करते हैं — साहसी, स्पष्ट, और जहाँ अन्य ठिठकें वहाँ पहले कदम बढ़ाने वाले। नेतृत्व आप पर सहज सजता है। इस अग्नि को एक समय में एक लक्ष्य दें; विजयें आपकी अधीरता से भी तेज़ पहुँचेंगी।" },
  { en: "Vrishabha rising gives you steadiness the world can build upon — patient, loyal, artistic, with a gift for creating lasting comfort and wealth. You finish what flightier people abandon. Welcome change occasionally; even the finest garden needs new seeds.", hi: "वृषभ लग्न आपको वह स्थिरता देता है जिस पर संसार भवन खड़ा कर सके — धैर्यवान, निष्ठावान, कला-प्रेमी, स्थायी सुख और संपत्ति रचने में कुशल। जो कार्य चंचल लोग छोड़ दें, आप पूर्ण करते हैं। कभी-कभी परिवर्तन का स्वागत करें; श्रेष्ठ उद्यान को भी नए बीज चाहिए।" },
  { en: "Mithuna rising makes you quicksilver-bright — curious, articulate, endlessly adaptable. You connect people and ideas effortlessly and learn anything fast. Choose depth for your favourite few subjects; the world rewards the brilliant specialist even more than the brilliant generalist.", hi: "मिथुन लग्न आपको पारद-सी चपल बुद्धि देता है — जिज्ञासु, वाक्पटु, हर परिस्थिति में ढल जाने वाले। आप व्यक्तियों और विचारों को सहज जोड़ देते हैं। अपने प्रिय विषयों में गहराई चुनिए; संसार प्रतिभाशाली विशेषज्ञ को और भी अधिक फल देता है।" },
  { en: "Karka rising gives you the strongest heart in the zodiac — intuitive, protective, and deeply loyal to home and roots. People heal in your care. Let logic partner your feelings in big decisions, and your legendary memory will store mostly the sweet.", hi: "कर्क लग्न आपको राशिचक्र का सबसे सशक्त हृदय देता है — सहज-बोधी, रक्षक, घर और जड़ों के प्रति गहरे निष्ठावान। आपकी छाया में लोग स्वस्थ होते हैं। बड़े निर्णयों में भावना के साथ तर्क को भी बैठाइए; तब आपकी विख्यात स्मृति अधिकतर मधुर ही संजोएगी।" },
  { en: "Simha rising crowns you with natural dignity — generous, warm, born for the centre of meaningful stages. Your confidence lifts entire rooms. Share the spotlight freely and praise others often; a king remembered for generosity rules forever.", hi: "सिंह लग्न आपको स्वाभाविक गरिमा का मुकुट देता है — उदार, ऊष्मापूर्ण, सार्थक मंचों के केंद्र के लिए जन्मे। आपका आत्मविश्वास पूरे सभागार को ऊपर उठाता है। प्रकाश बाँटिए और प्रशंसा खुलकर कीजिए; उदारता के लिए स्मरण किया गया राजा सदा राज करता है।" },
  { en: "Kanya rising gives you the craftsman's eye — precise, helpful, quietly brilliant at making systems and people function better. Your service is your worship. Release perfectionism toward yourself; you already exceed the standards you fear missing.", hi: "कन्या लग्न आपको शिल्पी की दृष्टि देता है — सूक्ष्म, सेवाभावी, व्यवस्थाओं और व्यक्तियों को बेहतर बनाने में मौन प्रतिभाशाली। सेवा ही आपकी पूजा है। स्वयं के प्रति पूर्णतावाद छोड़िए; जिन मापदंडों से चूकने का भय है, आप उन्हें पहले ही पार कर चुके हैं।" },
  { en: "Tula rising makes you the zodiac's diplomat-artist — balanced, gracious, with an instinct for fairness and beauty that draws people to you. Partnerships prosper around you. Practise deciding a little faster; your judgment is better than your doubt believes.", hi: "तुला लग्न आपको राशिचक्र का कूटनीतिज्ञ-कलाकार बनाता है — संतुलित, शालीन, न्याय और सौंदर्य की सहज समझ से लोग आपकी ओर खिंचते हैं। साझेदारियाँ आपके संग फलती हैं। निर्णय थोड़ा शीघ्र लेने का अभ्यास करें; आपका विवेक आपकी शंका से कहीं श्रेष्ठ है।" },
  { en: "Vrishchika rising gives you depth and regenerative power — you perceive hidden truths, survive what would break others, and return stronger every time. Your focus is a laser. Choose worthy targets and trusted confidants; then nothing in this world outlasts you.", hi: "वृश्चिक लग्न आपको गहराई और पुनर्जीवन की शक्ति देता है — आप छिपे सत्य देख लेते हैं, वह सह जाते हैं जो औरों को तोड़ दे, और हर बार प्रबल होकर लौटते हैं। आपकी एकाग्रता किरण-सी है। योग्य लक्ष्य और विश्वस्त साथी चुनिए; फिर इस संसार में कुछ भी आपसे अधिक टिक नहीं सकता।" },
  { en: "Dhanu rising fills you with the archer's optimism — philosophical, adventurous, honest to a fault, always aiming beyond the visible horizon. Fortune genuinely favours you. Aim, then also walk the full distance; arrows land where feet follow.", hi: "धनु लग्न आपको धनुर्धर का आशावाद देता है — दार्शनिक, साहसिक, स्पष्टवादी, सदा दृश्य क्षितिज से आगे लक्ष्य साधने वाले। भाग्य वास्तव में आपके पक्ष में रहता है। लक्ष्य साधिए, फिर पूरी दूरी चलिए भी; बाण वहीं पहुँचते हैं जहाँ चरण साथ चलते हैं।" },
  { en: "Makara rising gives you the mountain-climber's soul — disciplined, responsible, unhurried, and utterly unstoppable over time. You build things that outlive trends. Schedule joy as seriously as duty; the summit is for living, not only reaching.", hi: "मकर लग्न आपको पर्वतारोही की आत्मा देता है — अनुशासित, उत्तरदायी, अविचल, और समय के साथ पूर्णतः अजेय। आप वह रचते हैं जो प्रचलनों से आगे जीता है। आनंद को भी कर्तव्य जितनी गंभीरता से समय दीजिए; शिखर पहुँचने के लिए नहीं, जीने के लिए है।" },
  { en: "Kumbha rising makes you the visionary friend of humanity — original, principled, comfortable being years ahead of your time. Communities form around your ideas. Keep translating vision into small practical steps; the future arrives through them.", hi: "कुंभ लग्न आपको मानवता का दूरदर्शी मित्र बनाता है — मौलिक, सिद्धांतनिष्ठ, अपने समय से वर्षों आगे रहने में सहज। आपके विचारों के चारों ओर समुदाय बनते हैं। स्वप्न को छोटे व्यावहारिक चरणों में उतारते रहिए; भविष्य उन्हीं से होकर आता है।" },
  { en: "Meena rising gives you the ocean's compassion — imaginative, intuitive, spiritually gifted, dissolving boundaries between yourself and those who suffer. Art and devotion flow through you. Anchor your days with one firm routine; the ocean is mightiest with a shore.", hi: "मीन लग्न आपको सागर-सी करुणा देता है — कल्पनाशील, अंतर्दृष्टि-संपन्न, आध्यात्मिक प्रतिभा से युक्त, दुखियों और स्वयं के बीच की सीमा मिटा देने वाले। कला और भक्ति आपसे होकर बहती है। दिन को एक दृढ़ नियम से बाँधिए; तट के संग ही सागर सर्वाधिक शक्तिशाली होता है।" },
];
C.dashaLord={
  ketu: { en: "Ketu Mahadasha (7 years) turns life inward — a period of spiritual ripening, sudden insights, and release of what no longer serves. Material events may feel unpredictable, but inner growth is guaranteed. Best used for sadhana, research, and letting go gracefully.", hi: "केतु महादशा (7 वर्ष) जीवन को अंतर्मुखी करती है — आध्यात्मिक परिपक्वता, आकस्मिक बोध और अनावश्यक के त्याग का काल। बाह्य घटनाएँ अनिश्चित लग सकती हैं, पर आंतरिक विकास निश्चित है। साधना, शोध और सहज त्याग के लिए यह श्रेष्ठ समय है।" },
  venus: { en: "Shukra Mahadasha (20 years) is the season of love, comfort and creativity — relationships deepen, arts flourish, and material pleasures arrive generously. Wealth grows through people skills and aesthetics. Enjoy nobly and stay disciplined; sweetness lasts when savoured slowly.", hi: "शुक्र महादशा (20 वर्ष) प्रेम, सुख और सृजन का ऋतुकाल है — संबंध गहराते हैं, कलाएँ खिलती हैं, भौतिक सुख उदारता से आते हैं। धन जन-कौशल और सौंदर्य-दृष्टि से बढ़ता है। कुलीनता से आनंद लीजिए और संयम रखिए; धीरे चखी गई मिठास ही देर तक टिकती है।" },
  sun: { en: "Surya Mahadasha (6 years) brings authority and visibility — recognition from superiors, government matters, and leadership roles activate. Your name shines brighter. Health of father and your own vitality deserve care; humility keeps the crown steady.", hi: "सूर्य महादशा (6 वर्ष) अधिकार और प्रतिष्ठा लाती है — वरिष्ठों से मान, शासकीय कार्य और नेतृत्व की भूमिकाएँ सक्रिय होती हैं। आपका नाम अधिक चमकता है। पिता के स्वास्थ्य और अपनी ऊर्जा का ध्यान रखें; विनम्रता ही मुकुट को स्थिर रखती है।" },
  moon: { en: "Chandra Mahadasha (10 years) softens and enriches life — mind becomes receptive, public support grows, home and mother themes become central, and travel across waters is indicated. Emotional self-care is your superpower now; a calm moon commands the tides.", hi: "चंद्र महादशा (10 वर्ष) जीवन को कोमल और समृद्ध करती है — मन ग्रहणशील होता है, जन-समर्थन बढ़ता है, घर और माता के विषय केंद्र में आते हैं, जल-पार यात्रा के योग बनते हैं। मन की देखभाल अभी आपकी महाशक्ति है; शांत चंद्रमा ही ज्वार पर शासन करता है।" },
  mars: { en: "Mangal Mahadasha (7 years) ignites courage and action — property matters, competitions, technical skills, and physical energy all surge. Bold moves succeed now. Channel heat through exercise and clear goals; a directed flame forges, a wild one burns.", hi: "मंगल महादशा (7 वर्ष) साहस और कर्म प्रज्वलित करती है — भूमि-संपत्ति, प्रतियोगिताएँ, तकनीकी कौशल और शारीरिक ऊर्जा, सब बढ़ते हैं। साहसिक कदम अभी सफल होते हैं। इस ताप को व्यायाम और स्पष्ट लक्ष्य दें; दिशा-युक्त अग्नि गढ़ती है, दिशाहीन जलाती है।" },
  rahu: { en: "Rahu Mahadasha (18 years) is the great amplifier — foreign connections, technology, unconventional paths and sudden rises mark this era. Ambitions realized here can be enormous. Verify shortcuts and keep dharma as your compass; Rahu rewards the bold-with-ethics richly.", hi: "राहु महादशा (18 वर्ष) महान वर्धक है — विदेश-संबंध, तकनीक, अपरंपरागत मार्ग और आकस्मिक उत्थान इस युग की पहचान हैं। यहाँ पूर्ण हुई महत्वाकांक्षाएँ विशाल हो सकती हैं। शॉर्टकट परख लें और धर्म को दिशासूचक रखें; नीति-युक्त साहसी को राहु भरपूर देता है।" },
  jupiter: { en: "Guru Mahadasha (16 years) is the golden season of wisdom and grace — education, children, spiritual growth, respected mentors and honourable prosperity all expand. Blessings often arrive through teachers and your own teaching. Give knowledge freely; Guru returns it multiplied.", hi: "गुरु महादशा (16 वर्ष) ज्ञान और कृपा का स्वर्णकाल है — विद्या, संतान, आध्यात्मिक उन्नति, सम्मानित मार्गदर्शक और मर्यादित समृद्धि, सबका विस्तार होता है। आशीर्वाद प्रायः गुरुजनों से और आपके अपने शिक्षण से आते हैं। ज्ञान मुक्त हस्त से दीजिए; गुरु उसे कई गुना लौटाते हैं।" },
  saturn: { en: "Shani Mahadasha (19 years) builds your permanent legacy — through patience, discipline and honest labour, structures rise that nothing can shake. Rewards may come slowly but they come surely and stay. Serve the humble, respect time, and Shani becomes your strongest ally.", hi: "शनि महादशा (19 वर्ष) आपकी स्थायी विरासत गढ़ती है — धैर्य, अनुशासन और निष्कपट परिश्रम से ऐसे आधार बनते हैं जिन्हें कोई हिला न सके। फल धीमे आएँ पर निश्चित आते हैं और टिकते हैं। दीन की सेवा करें, समय का मान रखें; तब शनि आपके प्रबलतम मित्र बन जाते हैं।" },
  mercury: { en: "Budha Mahadasha (17 years) sharpens intellect and commerce — communication, business, writing, analytics and networks thrive. Multiple income streams become natural. Keep learning new skills each year; Budha crowns the perpetual student with green prosperity.", hi: "बुध महादशा (17 वर्ष) बुद्धि और व्यापार को तीक्ष्ण करती है — संवाद, व्यवसाय, लेखन, विश्लेषण और संपर्क-जाल फलते-फूलते हैं। आय के अनेक स्रोत सहज बनते हैं। प्रतिवर्ष नया कौशल सीखते रहिए; बुध नित्य-विद्यार्थी को हरित समृद्धि का मुकुट पहनाते हैं।" },
};
C.remedy={
  sun: { name: "Surya", mantra: "ॐ घृणिः सूर्याय नमः", en: "Offer water to the rising Sun; respect father and elders; donate wheat or jaggery on Sundays.", hi: "उगते सूर्य को जल अर्पित करें; पिता व गुरुजनों का सम्मान करें; रविवार को गेहूँ या गुड़ का दान करें।" },
  moon: { name: "Chandra", mantra: "ॐ सों सोमाय नमः", en: "Keep Monday calm and clean; honour mother; offer milk or rice to the needy on Mondays.", hi: "सोमवार शांत व सात्विक रखें; माता का आदर करें; सोमवार को दूध या चावल का दान करें।" },
  mars: { name: "Mangal", mantra: "ॐ अं अंगारकाय नमः", en: "Recite Hanuman Chalisa on Tuesdays; practise physical discipline; donate masoor dal or red cloth.", hi: "मंगलवार को हनुमान चालीसा पढ़ें; शारीरिक अनुशासन रखें; मसूर दाल या लाल वस्त्र का दान करें।" },
  mercury: { name: "Budha", mantra: "ॐ बुं बुधाय नमः", en: "Feed green fodder to cows on Wednesdays; keep speech truthful and sweet; donate green moong.", hi: "बुधवार को गौ को हरा चारा खिलाएँ; वाणी सत्य और मधुर रखें; हरे मूँग का दान करें।" },
  jupiter: { name: "Guru", mantra: "ॐ बृं बृहस्पतये नमः", en: "Serve teachers and share knowledge on Thursdays; donate turmeric, chana dal or books.", hi: "गुरुवार को गुरुजनों की सेवा और ज्ञान-दान करें; हल्दी, चने की दाल या पुस्तकों का दान करें।" },
  venus: { name: "Shukra", mantra: "ॐ शुं शुक्राय नमः", en: "Keep Fridays artistic and generous; respect women; donate white sweets, rice or curd.", hi: "शुक्रवार को कला और उदारता से जोड़ें; स्त्रियों का सम्मान करें; श्वेत मिष्ठान, चावल या दही का दान करें।" },
  saturn: { name: "Shani", mantra: "ॐ शं शनैश्चराय नमः", en: "Serve the elderly, workers and the disabled on Saturdays; light a sesame-oil lamp; donate black til or iron.", hi: "शनिवार को वृद्धों, श्रमिकों और असहायों की सेवा करें; तिल के तेल का दीप जलाएँ; काले तिल या लोहे का दान करें।" },
  rahu: { name: "Rahu", mantra: "ॐ रां राहवे नमः", en: "Maintain ethical clarity in ambitions; feed birds; donate blankets to the poor on Saturdays.", hi: "महत्वाकांक्षाओं में नैतिक स्पष्टता रखें; पक्षियों को दाना डालें; शनिवार को निर्धनों को कंबल दान करें।" },
  ketu: { name: "Ketu", mantra: "ॐ कें केतवे नमः", en: "Practise daily meditation or japa; care for stray dogs; donate multicoloured blankets or til.", hi: "नित्य ध्यान या जप करें; निराश्रित श्वानों की देखभाल करें; चितकबरे कंबल या तिल का दान करें।" },
};
C.yoga={
  gajaKesari: { en: "Gaja Kesari Yoga — Jupiter blesses your Moon from a kendra: wisdom, reputation and lasting respect grow throughout life; elders and institutions favour you.", hi: "गजकेसरी योग — गुरु आपके चंद्रमा को केंद्र से आशीर्वाद देते हैं: बुद्धि, कीर्ति और स्थायी सम्मान जीवन भर बढ़ते हैं; गुरुजन और संस्थाएँ आपके पक्ष में रहती हैं।" },
  budhaditya: { en: "Budhaditya Yoga — Sun and Mercury unite: sharp intellect, administrative talent and success in studies, writing and analysis.", hi: "बुधादित्य योग — सूर्य और बुध का मिलन: तीक्ष्ण बुद्धि, प्रशासनिक प्रतिभा और अध्ययन, लेखन व विश्लेषण में सफलता।" },
  chandraMangal: { en: "Chandra-Mangal Yoga — Moon with Mars: earning power, enterprise and the courage to act on feelings; wealth through self-effort.", hi: "चंद्र-मंगल योग — चंद्र संग मंगल: अर्जन-शक्ति, उद्यम और भावना को कर्म में बदलने का साहस; स्व-पुरुषार्थ से धन।" },
  ruchaka: { en: "Ruchaka Yoga (Mahapurusha) — Mars strong in a kendra: courage, command and physical excellence mark your path; a natural warrior-leader.", hi: "रुचक योग (पंचमहापुरुष) — केंद्र में बली मंगल: साहस, नेतृत्व-आदेश और शारीरिक श्रेष्ठता आपके पथ की पहचान; स्वाभाविक योद्धा-नायक।" },
  bhadra: { en: "Bhadra Yoga (Mahapurusha) — Mercury strong in a kendra: brilliant intellect, eloquence and enduring youthful charm; success in commerce and communication.", hi: "भद्र योग (पंचमहापुरुष) — केंद्र में बली बुध: प्रखर बुद्धि, वाक्पटुता और चिर-यौवन आकर्षण; वाणिज्य और संवाद में सफलता।" },
  hamsa: { en: "Hamsa Yoga (Mahapurusha) — Jupiter strong in a kendra: righteousness, learning and honour; you are respected like a swan among birds.", hi: "हंस योग (पंचमहापुरुष) — केंद्र में बली गुरु: धर्मनिष्ठा, विद्या और मान; पक्षियों में हंस-सा आदर आपको प्राप्त है।" },
  malavya: { en: "Malavya Yoga (Mahapurusha) — Venus strong in a kendra: refinement, artistic gifts, vehicles, comforts and a gracious married life are indicated.", hi: "मालव्य योग (पंचमहापुरुष) — केंद्र में बली शुक्र: परिष्कार, कला-प्रतिभा, वाहन-सुख और सौम्य दांपत्य जीवन के संकेत।" },
  shasha: { en: "Shasha Yoga (Mahapurusha) — Saturn strong in a kendra: authority over people and land, discipline and durable power, especially in later life.", hi: "शश योग (पंचमहापुरुष) — केंद्र में बली शनि: जन और भूमि पर अधिकार, अनुशासन और स्थायी सत्ता, विशेषतः उत्तरार्ध जीवन में।" },
  harsha: { en: "Harsha Yoga (Vipreet) — hardships transform into happiness; enemies retreat and health strengthens after challenges.", hi: "हर्ष योग (विपरीत राजयोग) — कठिनाइयाँ सुख में बदलती हैं; चुनौतियों के बाद शत्रु पीछे हटते हैं और स्वास्थ्य सुदृढ़ होता है।" },
  sarala: { en: "Sarala Yoga (Vipreet) — fearlessness and victory through crises; what threatens others becomes your ladder.", hi: "सरल योग (विपरीत राजयोग) — संकटों के बीच निर्भयता और विजय; जो औरों के लिए भय है, वही आपकी सीढ़ी बनता है।" },
  vimala: { en: "Vimala Yoga (Vipreet) — economy of expenses, independence and a spotless reputation grow with time.", hi: "विमल योग (विपरीत राजयोग) — व्यय-संयम, स्वावलंबन और निष्कलंक कीर्ति समय के साथ बढ़ती है।" },
  raja: { en: "Raja Yoga — lords of kendra and trikona unite: rise in status, favour from authority and success that uplifts your whole family line.", hi: "राजयोग — केंद्र और त्रिकोण के स्वामियों का मिलन: पद-प्रतिष्ठा में उत्थान, सत्ता की कृपा और ऐसी सफलता जो पूरे कुल को ऊपर उठाए।" },
  dhana: { en: "Dhana Yoga — wealth lords combine: strong earning combinations; prosperity grows through multiple streams.", hi: "धन योग — धनेश-लाभेश का संयोग: प्रबल अर्जन-योग; अनेक स्रोतों से समृद्धि बढ़ती है।" },
  kemadruma: { en: "Kemadruma is indicated by the Moon standing alone — early struggles are possible, yet classical texts list many cancellations, and self-made success is this yoga's famous other face. Steady sadhana and good company dissolve its shadow.", hi: "केमद्रुम योग — चंद्रमा का एकाकी होना: प्रारंभिक संघर्ष संभव हैं, किंतु शास्त्रों में इसके अनेक भंग-नियम हैं, और स्वयं-निर्मित सफलता इसी योग का प्रसिद्ध दूसरा मुख है। नित्य साधना और सत्संग इसकी छाया मिटा देते हैं।" },
};
C.dosha={
  manglikYes:{en:"Mangal Dosha is present in the Lagna chart (Mars influences the marriage houses). Classical texts prescribe many cancellations and it commonly softens greatly after age 28; matching with a compatible chart and Mangal sadhana (Hanuman upasana on Tuesdays) are the time-honoured paths.",hi:"लग्न कुंडली में मंगल दोष है (मंगल विवाह-भावों को प्रभावित करता है)। शास्त्रों में इसके अनेक परिहार हैं और 28 वर्ष की आयु के बाद यह प्रायः बहुत शांत हो जाता है; अनुकूल कुंडली से मिलान तथा मंगलवार को हनुमान-उपासना इसके शास्त्रसम्मत मार्ग हैं।"},
  manglikNo:{en:"No Mangal Dosha in the Lagna chart — Mars sits peacefully for marriage matters.",hi:"लग्न कुंडली में मंगल दोष नहीं है — विवाह के विषय में मंगल शांत स्थित हैं।"},
  kaalSarpYes:{en:"A Kaal Sarpa configuration is present ({type}). Tradition reads it as concentrated karmic focus: extraordinary rises follow disciplined effort. Rahu-Ketu shanti, Nag Panchami observance and steady japa are the classical supports.",hi:"कुंडली में कालसर्प स्थिति ({type}) विद्यमान है। परंपरा इसे केंद्रित कर्म-शक्ति मानती है: अनुशासित पुरुषार्थ के बाद असाधारण उत्थान आते हैं। राहु-केतु शांति, नागपंचमी व्रत और नियमित जप इसके शास्त्रीय आधार हैं।"},
  kaalSarpNo:{en:"No Kaal Sarpa configuration — the planets stand freely on both sides of the nodal axis.",hi:"कालसर्प स्थिति नहीं है — ग्रह राहु-केतु अक्ष के दोनों ओर मुक्त स्थित हैं।"},
  sadeSatiActive:{en:"Saturn is currently transiting your Sade Sati zone ({phase}). This is Shani the teacher, not the punisher: responsibilities deepen, foundations get tested and rebuilt stronger. Discipline, humility and Saturday seva convert this period into lifelong assets.",hi:"शनि इस समय आपके साढ़े साती क्षेत्र ({phase}) में गोचर कर रहे हैं। यह दंड नहीं, शिक्षक-शनि हैं: उत्तरदायित्व गहराते हैं, नींव परखी जाकर और सुदृढ़ होती है। अनुशासन, विनम्रता और शनिवार की सेवा इस काल को आजीवन पूँजी में बदल देती है।"},
  sadeSatiNo:{en:"Sade Sati is not active at present. The next period is shown in the table with exact dates — awareness in advance is itself half the remedy.",hi:"वर्तमान में साढ़े साती सक्रिय नहीं है। आगामी अवधि तालिका में तिथियों सहित दी गई है — पूर्व-जानकारी स्वयं आधा उपाय है।"}
};
C.labels={
  reportTitle:{en:"Janma Kundli Report",hi:"जन्म कुंडली रिपोर्ट"},
  by:{en:"Shubh Din · shubhdin.app",hi:"शुभ दिन · shubhdin.app"},
  free:{en:"Complete Kundli — Free, Accurate, Verifiable",hi:"संपूर्ण कुंडली — निःशुल्क, शुद्ध, सत्यापन-योग्य"},
  birthPanchang:{en:"Birth Panchang",hi:"जन्म पंचांग"},
  charts:{en:"Kundli Charts",hi:"कुंडली चक्र"},
  positions:{en:"Planetary Positions",hi:"ग्रह स्थिति"},
  yourNak:{en:"Your Birth Nakshatra",hi:"आपका जन्म नक्षत्र"},
  yourLagna:{en:"Your Lagna (Ascendant)",hi:"आपका लग्न"},
  yogasFound:{en:"Auspicious Yogas in Your Kundli",hi:"आपकी कुंडली के शुभ योग"},
  dignity:{en:"Planetary Dignities",hi:"ग्रह-गरिमा"},
  ashtak:{en:"Sarvashtakavarga (House Strength)",hi:"सर्वाष्टकवर्ग (भाव-बल)"},
  doshas:{en:"Dosha Analysis — with honest context",hi:"दोष विश्लेषण — संतुलित दृष्टि सहित"},
  dashaTimeline:{en:"Vimshottari Dasha Timeline",hi:"विंशोत्तरी दशा क्रम"},
  currentDasha:{en:"Your Current Period",hi:"आपकी वर्तमान दशा"},
  sadeSati:{en:"Shani Sade Sati Periods",hi:"शनि साढ़े साती अवधियाँ"},
  remedies:{en:"Remedies as Sadhana",hi:"उपाय — साधना रूप में"},
  remedyNote:{en:"Shubh Din prescribes no gemstones and sells nothing. These classical remedies cost only devotion: mantra, seva and daan.",hi:"शुभ दिन कोई रत्न नहीं बताता, कुछ नहीं बेचता। ये शास्त्रीय उपाय केवल श्रद्धा माँगते हैं: मंत्र, सेवा और दान।"},
  verify:{en:"Every calculation in this report follows Drik Ganita (Lahiri ayanamsa) and can be verified against any standard panchang. Guidance is offered in the spirit of tradition, for reflection — your karma and effort remain supreme.",hi:"इस रिपोर्ट की प्रत्येक गणना दृक् गणित (लाहिरी अयनांश) से है और किसी भी मानक पंचांग से सत्यापित की जा सकती है। मार्गदर्शन परंपरा की भावना से, चिंतन हेतु है — आपका कर्म और पुरुषार्थ ही सर्वोपरि है।"},
  house:{en:"House",hi:"भाव"}, rashiW:{en:"Rashi",hi:"राशि"}, from:{en:"From",hi:"से"}, to:{en:"To",hi:"तक"}
};
})(typeof window!=='undefined'?window:global);
