// SHUBH DIN — apply-kundli-hi.js : applies report-strings.hi.json into report-content.js
// Companion to apply-kundli.js (which handles te). Same key format.
const fs=require('fs');
global.window=global; require('./report-content.js'); const C=global.SD_CONTENT;
const M=JSON.parse(fs.readFileSync('report-strings.hi.json','utf8'));
let n=0; const bad=[];
for(const key of Object.keys(M)){
  const m=key.match(/^kundli\.(.+)\.(en|t_en|\w+En)$/);
  if(!m){ bad.push(key+' (unparseable)'); continue; }
  const tf = m[2]==='en'?'hi' : m[2]==='t_en'?'t_hi' : m[2].slice(0,-2)+'Hi';
  let o=C, ok=true;
  for(const part of m[1].split('.')){
    const a=part.match(/^(\w+)\[(\d+)\]$/);
    o = a ? (o&&o[a[1]]&&o[a[1]][+a[2]]) : (o&&o[part]);
    if(o==null){ ok=false; break; }
  }
  if(!ok){ bad.push(key+' (path not found)'); continue; }
  o[tf]=M[key]; n++;
}
console.log('applied:',n);
if(bad.length){ console.error('✗ PROBLEM KEYS:',bad.length); bad.slice(0,8).forEach(b=>console.error('   •',b)); process.exit(1); }
const header='// SHUBH DIN — free Kundli content (multi-language)\n'+
 '// GENERATED by localization pipeline. DO NOT HAND-EDIT (Language Bible rule 3).\n'+
 '// Sources: report-strings.hi.json / report-strings.te.json\n'+
 '// Regenerated: '+new Date().toISOString()+'\n';
fs.writeFileSync('report-content.js', header+'(function(g){g.SD_CONTENT='+JSON.stringify(C)+';})(typeof window!==\'undefined\'?window:global);\n','utf8');
console.log('✓ report-content.js regenerated');
