// SHUBH DIN — apply-kundli.js
// Applies report-strings.<lang>.json into report-content.js (SD_CONTENT, free Kundli).
// Separate from apply-strings.js because SD_CONTENT is a flat multi-section object
// with array sections (bhava[0], nakshatra[3], ...), not a per-report namespace.
//
// Usage: node apply-kundli.js <lang>        e.g. node apply-kundli.js te
// Keys look like: "kundli.labels.reportTitle.en", "kundli.bhava[0].t_en"

const fs = require('fs');
const lang = process.argv[2];
if (!lang) { console.error('Usage: node apply-kundli.js <lang>'); process.exit(1); }

global.window = global;
require('./report-content.js');
const C = global.SD_CONTENT;

const file = `report-strings.${lang}.json`;
const MAP = JSON.parse(fs.readFileSync(file, 'utf8'));

function targetField(srcField) {
  if (srcField === 'en') return lang;
  if (srcField === 't_en') return 't_' + lang;
  if (/En$/.test(srcField)) return srcField.slice(0, -2) + lang.charAt(0).toUpperCase() + lang.slice(1);
  return null;
}

let applied = 0;
const bad = [];

for (const key of Object.keys(MAP)) {
  const m = key.match(/^kundli\.(.+)\.(en|t_en|\w+En)$/);
  if (!m) { bad.push(key + ' (unparseable)'); continue; }
  const path = m[1], srcField = m[2];
  const tf = targetField(srcField);
  let o = C;
  let ok = true;
  for (const part of path.split('.')) {
    const arr = part.match(/^(\w+)\[(\d+)\]$/);
    if (arr) { o = o && o[arr[1]] && o[arr[1]][+arr[2]]; }
    else { o = o && o[part]; }
    if (o === undefined || o === null) { ok = false; break; }
  }
  if (!ok) { bad.push(key + ' (path not found)'); continue; }
  if (o[srcField] === undefined) { bad.push(key + ' (no ' + srcField + ' at path)'); continue; }
  o[tf] = MAP[key];
  applied++;
}

console.log('applied:', applied);
if (bad.length) {
  console.error('✗ PROBLEM KEYS:', bad.length);
  bad.slice(0, 10).forEach(b => console.error('   •', b));
  console.error('Aborting — nothing written.');
  process.exit(1);
}

// coverage report
let total = 0, have = 0;
(function walk(o) {
  if (!o || typeof o !== 'object') return;
  if (Array.isArray(o)) { o.forEach(walk); return; }
  for (const k of Object.keys(o)) {
    const v = o[k];
    if ((k === 'en' || k === 't_en' || /En$/.test(k)) && (typeof v === 'string' || Array.isArray(v))) {
      total++;
      const tf = targetField(k);
      if (o[tf] !== undefined && o[tf] !== '') have++;
    } else if (typeof v === 'object') walk(v);
  }
})(C);

const header =
  '// SHUBH DIN — free Kundli content (multi-language)\n' +
  '// GENERATED by localization pipeline. DO NOT HAND-EDIT (Language Bible rule 3).\n' +
  '// Source of truth: report-strings.<lang>.json — edit, then: node apply-kundli.js <lang>\n' +
  '// Regenerated: ' + new Date().toISOString() + '\n';

fs.writeFileSync('report-content.js',
  header + '(function(g){g.SD_CONTENT=' + JSON.stringify(C) + ';})(typeof window!==\'undefined\'?window:global);\n',
  'utf8');

console.log(`✓ report-content.js regenerated — ${lang} coverage: ${have}/${total} (${Math.round(have / total * 100)}%)`);
