// SHUBH DIN — Localization: apply rewritten strings and regenerate a content file.
// Generic: works for any report, any language.
//
// Usage:
//   node apply-strings.js <report> <lang>
//   e.g. node apply-strings.js love hi
//
// Reads : <report>-content.js  (current structure)
//         <report>-strings.<lang>.json  (rewritten strings, keyed like "love.labels.title.en")
// Writes: <report>-content.js  (regenerated; DO NOT HAND-EDIT thereafter)
//
// Language Bible rules enforced:
//   - rule 3: JSON is the editable source; JS is generated
//   - avoid-list scan (rule H1) runs automatically for Hindi
//   - fails loudly on unmapped keys so translations never silently fall behind (rule 6)

const fs = require('fs');

const report = process.argv[2];
const lang = process.argv[3];
if (!report || !lang) {
  console.error('Usage: node apply-strings.js <report> <lang>   e.g. node apply-strings.js love hi');
  process.exit(1);
}

const GLOBALS = {
  love: 'SD_LOVE', marriage: 'SD_MARRIAGE', career: 'SD_CAREER', muhurta: 'SD_MUHURTA',
  forecast: 'SD_FORECAST', child: 'SD_CHILD', annual: 'SD_ANNUAL', report: 'SD_CONTENT'
};
const globalName = GLOBALS[report];
if (!globalName) { console.error('Unknown report:', report, '— known:', Object.keys(GLOBALS).join(', ')); process.exit(1); }

const contentFile = report + '-content.js';
const stringsFile = report + '-strings.' + lang + '.json';

global.window = global;
require('./' + contentFile);
const root = global[globalName];
if (!root) { console.error('Global', globalName, 'not found after loading', contentFile); process.exit(1); }

const MAP = JSON.parse(fs.readFileSync(stringsFile, 'utf8'));

// EN-bearing field -> target-language field for this lang
function langFieldFor(f) {
  const suffix = lang.charAt(0).toUpperCase() + lang.slice(1); // hi -> Hi, te -> Te
  if (f === 'en') return lang;                 // en -> hi
  if (f === 't_en') return 't_' + lang;        // t_en -> t_hi
  if (/En$/.test(f)) return f.slice(0, -2) + suffix; // doEn -> doHi, focusEn -> focusHi
  return null;
}
const isEnField = f => f === 'en' || f === 't_en' || /En$/.test(f);

let applied = 0;
const unmapped = [];
const usedKeys = new Set();

(function walk(obj, path) {
  if (obj === null || typeof obj !== 'object') return;
  if (Array.isArray(obj)) { obj.forEach((v, i) => walk(v, path + '[' + i + ']')); return; }
  for (const k of Object.keys(obj)) {
    const v = obj[k];
    if (isEnField(k) && (typeof v === 'string' || Array.isArray(v))) {
      const mapKey = path + '.' + k;
      if (MAP[mapKey] !== undefined) {
        obj[langFieldFor(k)] = MAP[mapKey];
        usedKeys.add(mapKey);
        applied++;
      } else {
        unmapped.push(mapKey);
      }
    } else if (typeof v === 'object') {
      walk(v, path + '.' + k);
    }
  }
})(root, report);

const strayKeys = Object.keys(MAP).filter(k => !usedKeys.has(k));

console.log('applied:', applied);
if (unmapped.length) console.error('✗ UNMAPPED (missing from ' + stringsFile + '):', unmapped.length, unmapped.slice(0, 8));
if (strayKeys.length) console.error('✗ STRAY keys in JSON (typos? no match in content):', strayKeys.length, strayKeys.slice(0, 8));
if (unmapped.length || strayKeys.length) { console.error('Aborting — fix the JSON, nothing written.'); process.exit(1); }

// Hindi avoid-list scan (Language Bible H1)
if (lang === 'hi') {
  const banned = ['प्रणय','उत्कटता','सुभेद्यता','अंतरंगता','विस्मय','उष्मा','विकास-किनारा','सुंदर संवाद','अभिव्यंजक','सहजबोध','कार्यसाध्य'];
  const hits = [];
  (function scan(o, p) {
    if (o === null || typeof o !== 'object') return;
    if (Array.isArray(o)) { o.forEach((v, i) => scan(v, p + '[' + i + ']')); return; }
    for (const k of Object.keys(o)) {
      const v = o[k];
      const isLangField = k === 'hi' || k === 't_hi' || /Hi$/.test(k);
      if (typeof v === 'string' && isLangField) {
        banned.forEach(b => { if (v.includes(b)) hits.push(p + '.' + k + ' → ' + b); });
      } else if (Array.isArray(v) && isLangField) {
        v.forEach(s => banned.forEach(b => { if (typeof s === 'string' && s.includes(b)) hits.push(p + '.' + k + ' → ' + b); }));
      } else if (typeof v === 'object') scan(v, p + '.' + k);
    }
  })(root, report);
  if (hits.length) { console.error('✗ AVOID-LIST VIOLATIONS (Bible H1):', hits.join('; ')); process.exit(1); }
  console.log('✓ avoid-list scan clean');
}

const header =
  '// SHUBH DIN — ' + report + ' content (multi-language)\n' +
  '// GENERATED by localization pipeline. DO NOT HAND-EDIT (Language Bible rule 3).\n' +
  '// Source of truth: ' + stringsFile + ' — edit that, then: node apply-strings.js ' + report + ' ' + lang + '\n' +
  '// Regenerated: ' + new Date().toISOString() + '\n';

fs.writeFileSync(contentFile,
  header + '(function(g){g.' + globalName + '=' + JSON.stringify(root) + ';})(typeof window!==\'undefined\'?window:global);\n',
  'utf8');

console.log('✓', contentFile, 'regenerated');
